coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 80%

flags:
  backend:
    paths:
      - backend/
  frontend:
    paths:
      - frontend/
