/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated user */
        get: operations["get-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Owner sailing summary */
        get: operations["get-dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List trainings */
        get: operations["list-trainings"];
        put?: never;
        /** Create a training */
        post: operations["create-training"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainings/{trainingID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a training */
        get: operations["get-training"];
        /** Update a training */
        put: operations["update-training"];
        post?: never;
        /** Delete a training */
        delete: operations["delete-training"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List trips */
        get: operations["list-trips"];
        put?: never;
        /** Create a trip */
        post: operations["create-trip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a trip */
        get: operations["get-trip"];
        /** Update a trip */
        put: operations["update-trip"];
        post?: never;
        /** Delete a trip */
        delete: operations["delete-trip"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripID}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a trip */
        post: operations["cancel-trip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripID}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a trip into a voyage */
        post: operations["complete-trip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voyages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List voyages */
        get: operations["list-voyages"];
        put?: never;
        /** Create a voyage */
        post: operations["create-voyage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voyages/{voyageID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a voyage */
        get: operations["get-voyage"];
        /** Update a voyage */
        put: operations["update-voyage"];
        post?: never;
        /** Delete a voyage */
        delete: operations["delete-voyage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yachts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List yachts */
        get: operations["list-yachts"];
        put?: never;
        /** Create a yacht */
        post: operations["create-yacht"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yachts/{yachtID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a yacht */
        get: operations["get-yacht"];
        /** Update a yacht */
        put: operations["update-yacht"];
        post?: never;
        /** Delete a yacht */
        delete: operations["delete-yacht"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CompleteTripBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/CompleteTripBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            days?: number;
            /** Format: double */
            hours_engine?: number;
            /** Format: double */
            hours_over_6bf?: number;
            /** Format: double */
            hours_sail?: number;
            /** Format: double */
            hours_total?: number;
            /** Format: double */
            miles?: number;
            /** Format: int64 */
            tidal_waters?: number;
            /** Format: int64 */
            year?: number;
        };
        Dashboard: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/Dashboard.json
             */
            readonly $schema?: string;
            by_year: components["schemas"]["VoyagesByYear"][] | null;
            /** Format: int64 */
            total_days: number;
            /** Format: double */
            total_hours: number;
            /** Format: double */
            total_hours_engine: number;
            /** Format: double */
            total_hours_sail: number;
            /** Format: double */
            total_miles: number;
            /** Format: int64 */
            voyage_count: number;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        Me: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/Me.json
             */
            readonly $schema?: string;
            avatar_url: string;
            email: string;
            /** Format: int64 */
            id: number;
            name: string;
        };
        Training: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/Training.json
             */
            readonly $schema?: string;
            /** Format: double */
            cost?: number;
            /** Format: date-time */
            created_at: string;
            date?: string;
            /** Format: int64 */
            id: number;
            name: string;
            organizer?: string;
            /** Format: date-time */
            updated_at: string;
            url?: string;
            /** Format: int64 */
            user_id: number;
        };
        TrainingBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/TrainingBody.json
             */
            readonly $schema?: string;
            /** Format: double */
            cost?: number;
            date?: string;
            /** @description Training name */
            name: string;
            organizer?: string;
            url?: string;
        };
        Trip: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/Trip.json
             */
            readonly $schema?: string;
            captain_name?: string;
            /** Format: double */
            cost_per_person?: number;
            /** Format: double */
            cost_total?: number;
            countries?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            cruise_id?: number;
            description?: string;
            disembark_date?: string;
            embark_date?: string;
            end_port?: string;
            enroll_token?: string;
            /** Format: int64 */
            id: number;
            image_logo_url?: string;
            image_photo_url?: string;
            image_route_url?: string;
            /** Format: int64 */
            max_crew?: number;
            name: string;
            /** Format: int64 */
            org_id?: number;
            /** Format: int64 */
            owner_id: number;
            start_port?: string;
            /** @enum {string} */
            status: "planned" | "cancelled";
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            yacht_id?: number;
        };
        TripBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/TripBody.json
             */
            readonly $schema?: string;
            captain_name?: string;
            /** Format: double */
            cost_per_person?: number;
            /** Format: double */
            cost_total?: number;
            countries?: string;
            /** Format: int64 */
            cruise_id?: number;
            description?: string;
            disembark_date?: string;
            embark_date?: string;
            end_port?: string;
            image_logo_url?: string;
            image_photo_url?: string;
            image_route_url?: string;
            /** Format: int64 */
            max_crew?: number;
            /** @description Trip name */
            name: string;
            start_port?: string;
            /** Format: int64 */
            yacht_id?: number;
        };
        Voyage: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/Voyage.json
             */
            readonly $schema?: string;
            captain_name?: string;
            /** Format: double */
            cost_per_person?: number;
            /** Format: double */
            cost_total?: number;
            countries?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            cruise_id?: number;
            /** Format: int64 */
            days: number;
            description?: string;
            disembark_date?: string;
            embark_date?: string;
            end_port?: string;
            /** Format: double */
            hours_engine: number;
            /** Format: double */
            hours_over_6bf: number;
            /** Format: double */
            hours_sail: number;
            /** Format: double */
            hours_total: number;
            /** Format: int64 */
            id: number;
            image_logo_url?: string;
            image_photo_url?: string;
            image_route_url?: string;
            /** Format: double */
            miles: number;
            name: string;
            /** Format: int64 */
            org_id?: number;
            /** Format: int64 */
            owner_id: number;
            start_port?: string;
            /** Format: int64 */
            tidal_waters: number;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            yacht_id?: number;
            /** Format: int64 */
            year?: number;
        };
        VoyageBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/VoyageBody.json
             */
            readonly $schema?: string;
            captain_name?: string;
            /** Format: double */
            cost_per_person?: number;
            /** Format: double */
            cost_total?: number;
            countries?: string;
            /** Format: int64 */
            cruise_id?: number;
            /** Format: int64 */
            days?: number;
            description?: string;
            disembark_date?: string;
            embark_date?: string;
            end_port?: string;
            /** Format: double */
            hours_engine?: number;
            /** Format: double */
            hours_over_6bf?: number;
            /** Format: double */
            hours_sail?: number;
            /** Format: double */
            hours_total?: number;
            image_logo_url?: string;
            image_photo_url?: string;
            image_route_url?: string;
            /** Format: double */
            miles?: number;
            /** @description Voyage name */
            name: string;
            start_port?: string;
            /** Format: int64 */
            tidal_waters?: number;
            /** Format: int64 */
            yacht_id?: number;
            /** Format: int64 */
            year?: number;
        };
        VoyagesByYear: {
            /** Format: int64 */
            total_days: number;
            /** Format: double */
            total_hours: number;
            /** Format: double */
            total_miles: number;
            /** Format: int64 */
            voyage_count: number;
            /** Format: int64 */
            year?: number;
        };
        Yacht: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/Yacht.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            org_id?: number;
            /** Format: int64 */
            owner_id: number;
            registration_no?: string;
            /** Format: date-time */
            updated_at: string;
            yacht_type?: string;
        };
        YachtBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/YachtBody.json
             */
            readonly $schema?: string;
            /** @description Yacht name */
            name: string;
            registration_no?: string;
            yacht_type?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-trainings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Training"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-training": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Training"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-training": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Training ID */
                trainingID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Training"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-training": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Training ID */
                trainingID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrainingBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-training": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Training ID */
                trainingID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-trip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-trip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-trip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-trip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cancel-trip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "complete-trip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteTripBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Voyage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-voyages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Voyage"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-voyage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoyageBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Voyage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-voyage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Voyage ID */
                voyageID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Voyage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-voyage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Voyage ID */
                voyageID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoyageBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-voyage": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Voyage ID */
                voyageID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-yachts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Yacht"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-yacht": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YachtBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Yacht"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-yacht": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yacht ID */
                yachtID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Yacht"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-yacht": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yacht ID */
                yachtID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YachtBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-yacht": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Yacht ID */
                yachtID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
