/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List trips */
        get: operations["list-trips"];
        put?: never;
        /** Create a trip */
        post: operations["create-trip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a trip */
        get: operations["get-trip"];
        /** Update a trip */
        put: operations["update-trip"];
        post?: never;
        /** Delete a trip */
        delete: operations["delete-trip"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripID}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a trip */
        post: operations["cancel-trip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripID}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete a trip into a voyage */
        post: operations["complete-trip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/ApiError.json
             */
            readonly $schema?: string;
            /** @description Human-readable error message */
            error: string;
        };
        CompleteTripBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/CompleteTripBody.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            days?: number;
            /** Format: double */
            hours_engine?: number;
            /** Format: double */
            hours_over_6bf?: number;
            /** Format: double */
            hours_sail?: number;
            /** Format: double */
            hours_total?: number;
            /** Format: double */
            miles?: number;
            /** Format: int64 */
            tidal_waters?: number;
            /** Format: int64 */
            year?: number;
        };
        Trip: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/Trip.json
             */
            readonly $schema?: string;
            captain_name?: string;
            /** Format: double */
            cost_per_person?: number;
            /** Format: double */
            cost_total?: number;
            countries?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            cruise_id?: number;
            description?: string;
            disembark_date?: string;
            embark_date?: string;
            end_port?: string;
            enroll_token?: string;
            /** Format: int64 */
            id: number;
            image_logo_url?: string;
            image_photo_url?: string;
            image_route_url?: string;
            /** Format: int64 */
            max_crew?: number;
            name: string;
            /** Format: int64 */
            org_id?: number;
            /** Format: int64 */
            owner_id: number;
            start_port?: string;
            /** @enum {string} */
            status: "planned" | "cancelled";
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            yacht_id?: number;
        };
        TripBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/TripBody.json
             */
            readonly $schema?: string;
            captain_name?: string;
            /** Format: double */
            cost_per_person?: number;
            /** Format: double */
            cost_total?: number;
            countries?: string;
            /** Format: int64 */
            cruise_id?: number;
            description?: string;
            disembark_date?: string;
            embark_date?: string;
            end_port?: string;
            image_logo_url?: string;
            image_photo_url?: string;
            image_route_url?: string;
            /** Format: int64 */
            max_crew?: number;
            /** @description Trip name */
            name: string;
            start_port?: string;
            /** Format: int64 */
            yacht_id?: number;
        };
        Voyage: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example /api/Voyage.json
             */
            readonly $schema?: string;
            captain_name?: string;
            /** Format: double */
            cost_per_person?: number;
            /** Format: double */
            cost_total?: number;
            countries?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: int64 */
            cruise_id?: number;
            /** Format: int64 */
            days: number;
            description?: string;
            disembark_date?: string;
            embark_date?: string;
            end_port?: string;
            /** Format: double */
            hours_engine: number;
            /** Format: double */
            hours_over_6bf: number;
            /** Format: double */
            hours_sail: number;
            /** Format: double */
            hours_total: number;
            /** Format: int64 */
            id: number;
            image_logo_url?: string;
            image_photo_url?: string;
            image_route_url?: string;
            /** Format: double */
            miles: number;
            name: string;
            /** Format: int64 */
            org_id?: number;
            /** Format: int64 */
            owner_id: number;
            start_port?: string;
            /** Format: int64 */
            tidal_waters: number;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            yacht_id?: number;
            /** Format: int64 */
            year?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "create-trip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "get-trip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "update-trip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripBody"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "delete-trip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "cancel-trip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    "complete-trip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trip ID */
                tripID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteTripBody"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Voyage"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
