CREATE TABLE cruises (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    year INTEGER,
    embark_date TEXT,
    disembark_date TEXT,
    countries TEXT,
    start_port TEXT,
    end_port TEXT,
    hours_total REAL DEFAULT 0,
    hours_sail REAL DEFAULT 0,
    hours_engine REAL DEFAULT 0,
    hours_over_6bf REAL DEFAULT 0,
    miles REAL DEFAULT 0,
    days INTEGER DEFAULT 0,
    captain_name TEXT,
    yacht_id INTEGER REFERENCES yachts(id),
    tidal_waters INTEGER DEFAULT 0,
    cost_total REAL DEFAULT 0,
    cost_per_person REAL DEFAULT 0,
    image_logo_url TEXT,
    image_photo_url TEXT,
    image_route_url TEXT,
    description TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
