// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crew_members.sql

package sqlcdb

import (
	"context"

	types "github.com/marcinskalski/sailor-buddy/backend/internal/types"
)

const countCrewMembers = `-- name: CountCrewMembers :one
SELECT COUNT(*)::BIGINT FROM crew_members
`

// CountCrewMembers
//
//	SELECT COUNT(*)::BIGINT FROM crew_members
func (q *Queries) CountCrewMembers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCrewMembers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCrewMember = `-- name: CreateCrewMember :one
INSERT INTO crew_members (
    created_by, user_id, full_name, email, patent_number,
    phone, pzz_license_type, pzz_license_number,
    emergency_contact_name, emergency_contact_phone
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, created_by, user_id, full_name, email, patent_number, phone, pzz_license_type, pzz_license_number, emergency_contact_name, emergency_contact_phone, created_at, updated_at
`

type CreateCrewMemberParams struct {
	CreatedBy             types.NullInt64  `json:"created_by"`
	UserID                types.NullInt64  `json:"user_id"`
	FullName              string           `json:"full_name"`
	Email                 types.NullString `json:"email"`
	PatentNumber          types.NullString `json:"patent_number"`
	Phone                 types.NullString `json:"phone"`
	PzzLicenseType        types.NullString `json:"pzz_license_type"`
	PzzLicenseNumber      types.NullString `json:"pzz_license_number"`
	EmergencyContactName  types.NullString `json:"emergency_contact_name"`
	EmergencyContactPhone types.NullString `json:"emergency_contact_phone"`
}

// CreateCrewMember
//
//	INSERT INTO crew_members (
//	    created_by, user_id, full_name, email, patent_number,
//	    phone, pzz_license_type, pzz_license_number,
//	    emergency_contact_name, emergency_contact_phone
//	) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, created_by, user_id, full_name, email, patent_number, phone, pzz_license_type, pzz_license_number, emergency_contact_name, emergency_contact_phone, created_at, updated_at
func (q *Queries) CreateCrewMember(ctx context.Context, arg CreateCrewMemberParams) (CrewMember, error) {
	row := q.db.QueryRowContext(ctx, createCrewMember,
		arg.CreatedBy,
		arg.UserID,
		arg.FullName,
		arg.Email,
		arg.PatentNumber,
		arg.Phone,
		arg.PzzLicenseType,
		arg.PzzLicenseNumber,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
	)
	var i CrewMember
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.UserID,
		&i.FullName,
		&i.Email,
		&i.PatentNumber,
		&i.Phone,
		&i.PzzLicenseType,
		&i.PzzLicenseNumber,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCrewMember = `-- name: DeleteCrewMember :exec
DELETE FROM crew_members WHERE id = $1
`

// DeleteCrewMember
//
//	DELETE FROM crew_members WHERE id = $1
func (q *Queries) DeleteCrewMember(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCrewMember, id)
	return err
}

const getCrewMember = `-- name: GetCrewMember :one
SELECT id, created_by, user_id, full_name, email, patent_number, phone, pzz_license_type, pzz_license_number, emergency_contact_name, emergency_contact_phone, created_at, updated_at FROM crew_members WHERE id = $1
`

// GetCrewMember
//
//	SELECT id, created_by, user_id, full_name, email, patent_number, phone, pzz_license_type, pzz_license_number, emergency_contact_name, emergency_contact_phone, created_at, updated_at FROM crew_members WHERE id = $1
func (q *Queries) GetCrewMember(ctx context.Context, id int64) (CrewMember, error) {
	row := q.db.QueryRowContext(ctx, getCrewMember, id)
	var i CrewMember
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.UserID,
		&i.FullName,
		&i.Email,
		&i.PatentNumber,
		&i.Phone,
		&i.PzzLicenseType,
		&i.PzzLicenseNumber,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCrewMemberByName = `-- name: GetCrewMemberByName :one
SELECT id, created_by, user_id, full_name, email, patent_number, phone, pzz_license_type, pzz_license_number, emergency_contact_name, emergency_contact_phone, created_at, updated_at FROM crew_members WHERE full_name = $1
`

// GetCrewMemberByName
//
//	SELECT id, created_by, user_id, full_name, email, patent_number, phone, pzz_license_type, pzz_license_number, emergency_contact_name, emergency_contact_phone, created_at, updated_at FROM crew_members WHERE full_name = $1
func (q *Queries) GetCrewMemberByName(ctx context.Context, fullName string) (CrewMember, error) {
	row := q.db.QueryRowContext(ctx, getCrewMemberByName, fullName)
	var i CrewMember
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.UserID,
		&i.FullName,
		&i.Email,
		&i.PatentNumber,
		&i.Phone,
		&i.PzzLicenseType,
		&i.PzzLicenseNumber,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCrewMembers = `-- name: ListCrewMembers :many
SELECT id, created_by, user_id, full_name, email, patent_number, phone, pzz_license_type, pzz_license_number, emergency_contact_name, emergency_contact_phone, created_at, updated_at FROM crew_members ORDER BY full_name, id LIMIT $1 OFFSET $2
`

type ListCrewMembersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// ListCrewMembers
//
//	SELECT id, created_by, user_id, full_name, email, patent_number, phone, pzz_license_type, pzz_license_number, emergency_contact_name, emergency_contact_phone, created_at, updated_at FROM crew_members ORDER BY full_name, id LIMIT $1 OFFSET $2
func (q *Queries) ListCrewMembers(ctx context.Context, arg ListCrewMembersParams) ([]CrewMember, error) {
	rows, err := q.db.QueryContext(ctx, listCrewMembers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrewMember
	for rows.Next() {
		var i CrewMember
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.UserID,
			&i.FullName,
			&i.Email,
			&i.PatentNumber,
			&i.Phone,
			&i.PzzLicenseType,
			&i.PzzLicenseNumber,
			&i.EmergencyContactName,
			&i.EmergencyContactPhone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCrewMember = `-- name: UpdateCrewMember :exec
UPDATE crew_members SET
    full_name = $1, email = $2, patent_number = $3,
    phone = $4, pzz_license_type = $5, pzz_license_number = $6,
    emergency_contact_name = $7, emergency_contact_phone = $8,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $9
`

type UpdateCrewMemberParams struct {
	FullName              string           `json:"full_name"`
	Email                 types.NullString `json:"email"`
	PatentNumber          types.NullString `json:"patent_number"`
	Phone                 types.NullString `json:"phone"`
	PzzLicenseType        types.NullString `json:"pzz_license_type"`
	PzzLicenseNumber      types.NullString `json:"pzz_license_number"`
	EmergencyContactName  types.NullString `json:"emergency_contact_name"`
	EmergencyContactPhone types.NullString `json:"emergency_contact_phone"`
	ID                    int64            `json:"id"`
}

// UpdateCrewMember
//
//	UPDATE crew_members SET
//	    full_name = $1, email = $2, patent_number = $3,
//	    phone = $4, pzz_license_type = $5, pzz_license_number = $6,
//	    emergency_contact_name = $7, emergency_contact_phone = $8,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $9
func (q *Queries) UpdateCrewMember(ctx context.Context, arg UpdateCrewMemberParams) error {
	_, err := q.db.ExecContext(ctx, updateCrewMember,
		arg.FullName,
		arg.Email,
		arg.PatentNumber,
		arg.Phone,
		arg.PzzLicenseType,
		arg.PzzLicenseNumber,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.ID,
	)
	return err
}
