// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crew_assignments.sql

package sqlcdb

import (
	"context"

	types "github.com/marcinskalski/sailor-buddy/backend/internal/types"
)

const createTripCrewAssignment = `-- name: CreateTripCrewAssignment :one
INSERT INTO crew_assignments (trip_id, crew_member_id, role, patent_number)
VALUES ($1, $2, $3, $4) RETURNING id, crew_member_id, role, patent_number, created_at, trip_id, voyage_id
`

type CreateTripCrewAssignmentParams struct {
	TripID       types.NullInt64  `json:"trip_id"`
	CrewMemberID int64            `json:"crew_member_id"`
	Role         string           `json:"role"`
	PatentNumber types.NullString `json:"patent_number"`
}

// CreateTripCrewAssignment
//
//	INSERT INTO crew_assignments (trip_id, crew_member_id, role, patent_number)
//	VALUES ($1, $2, $3, $4) RETURNING id, crew_member_id, role, patent_number, created_at, trip_id, voyage_id
func (q *Queries) CreateTripCrewAssignment(ctx context.Context, arg CreateTripCrewAssignmentParams) (CrewAssignment, error) {
	row := q.db.QueryRowContext(ctx, createTripCrewAssignment,
		arg.TripID,
		arg.CrewMemberID,
		arg.Role,
		arg.PatentNumber,
	)
	var i CrewAssignment
	err := row.Scan(
		&i.ID,
		&i.CrewMemberID,
		&i.Role,
		&i.PatentNumber,
		&i.CreatedAt,
		&i.TripID,
		&i.VoyageID,
	)
	return i, err
}

const createVoyageCrewAssignment = `-- name: CreateVoyageCrewAssignment :one
INSERT INTO crew_assignments (voyage_id, crew_member_id, role, patent_number)
VALUES ($1, $2, $3, $4) RETURNING id, crew_member_id, role, patent_number, created_at, trip_id, voyage_id
`

type CreateVoyageCrewAssignmentParams struct {
	VoyageID     types.NullInt64  `json:"voyage_id"`
	CrewMemberID int64            `json:"crew_member_id"`
	Role         string           `json:"role"`
	PatentNumber types.NullString `json:"patent_number"`
}

// CreateVoyageCrewAssignment
//
//	INSERT INTO crew_assignments (voyage_id, crew_member_id, role, patent_number)
//	VALUES ($1, $2, $3, $4) RETURNING id, crew_member_id, role, patent_number, created_at, trip_id, voyage_id
func (q *Queries) CreateVoyageCrewAssignment(ctx context.Context, arg CreateVoyageCrewAssignmentParams) (CrewAssignment, error) {
	row := q.db.QueryRowContext(ctx, createVoyageCrewAssignment,
		arg.VoyageID,
		arg.CrewMemberID,
		arg.Role,
		arg.PatentNumber,
	)
	var i CrewAssignment
	err := row.Scan(
		&i.ID,
		&i.CrewMemberID,
		&i.Role,
		&i.PatentNumber,
		&i.CreatedAt,
		&i.TripID,
		&i.VoyageID,
	)
	return i, err
}

const deleteTripCrewAssignment = `-- name: DeleteTripCrewAssignment :exec
DELETE FROM crew_assignments
WHERE crew_assignments.id = $1
  AND crew_assignments.trip_id IN (SELECT trips.id FROM trips WHERE trips.owner_id = $2)
`

type DeleteTripCrewAssignmentParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

// DeleteTripCrewAssignment
//
//	DELETE FROM crew_assignments
//	WHERE crew_assignments.id = $1
//	  AND crew_assignments.trip_id IN (SELECT trips.id FROM trips WHERE trips.owner_id = $2)
func (q *Queries) DeleteTripCrewAssignment(ctx context.Context, arg DeleteTripCrewAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteTripCrewAssignment, arg.ID, arg.OwnerID)
	return err
}

const deleteVoyageCrewAssignment = `-- name: DeleteVoyageCrewAssignment :exec
DELETE FROM crew_assignments
WHERE crew_assignments.id = $1
  AND crew_assignments.voyage_id IN (SELECT voyages.id FROM voyages WHERE voyages.owner_id = $2)
`

type DeleteVoyageCrewAssignmentParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

// DeleteVoyageCrewAssignment
//
//	DELETE FROM crew_assignments
//	WHERE crew_assignments.id = $1
//	  AND crew_assignments.voyage_id IN (SELECT voyages.id FROM voyages WHERE voyages.owner_id = $2)
func (q *Queries) DeleteVoyageCrewAssignment(ctx context.Context, arg DeleteVoyageCrewAssignmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteVoyageCrewAssignment, arg.ID, arg.OwnerID)
	return err
}

const getCrewMemberStats = `-- name: GetCrewMemberStats :one
SELECT
    COUNT(*)::BIGINT AS voyage_count,
    COALESCE(SUM(v.hours_total), 0)::DOUBLE PRECISION AS total_hours,
    COALESCE(SUM(v.miles), 0)::DOUBLE PRECISION AS total_miles,
    COALESCE(SUM(v.days), 0)::BIGINT AS total_days
FROM crew_assignments ca
JOIN voyages v ON v.id = ca.voyage_id
WHERE ca.crew_member_id = $1
`

type GetCrewMemberStatsRow struct {
	VoyageCount int64   `json:"voyage_count"`
	TotalHours  float64 `json:"total_hours"`
	TotalMiles  float64 `json:"total_miles"`
	TotalDays   int64   `json:"total_days"`
}

// GetCrewMemberStats
//
//	SELECT
//	    COUNT(*)::BIGINT AS voyage_count,
//	    COALESCE(SUM(v.hours_total), 0)::DOUBLE PRECISION AS total_hours,
//	    COALESCE(SUM(v.miles), 0)::DOUBLE PRECISION AS total_miles,
//	    COALESCE(SUM(v.days), 0)::BIGINT AS total_days
//	FROM crew_assignments ca
//	JOIN voyages v ON v.id = ca.voyage_id
//	WHERE ca.crew_member_id = $1
func (q *Queries) GetCrewMemberStats(ctx context.Context, crewMemberID int64) (GetCrewMemberStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getCrewMemberStats, crewMemberID)
	var i GetCrewMemberStatsRow
	err := row.Scan(
		&i.VoyageCount,
		&i.TotalHours,
		&i.TotalMiles,
		&i.TotalDays,
	)
	return i, err
}

const getCrewMemberTrips = `-- name: GetCrewMemberTrips :many
SELECT t.id, t.owner_id, t.org_id, t.name, t.embark_date, t.disembark_date, t.countries, t.start_port, t.end_port, t.captain_name, t.yacht_id, t.cost_total, t.cost_per_person, t.max_crew, t.image_logo_url, t.image_photo_url, t.image_route_url, t.description, t.status, t.enroll_token, t.created_at, t.updated_at, t.cruise_id, ca.role
FROM crew_assignments ca
JOIN trips t ON t.id = ca.trip_id
WHERE ca.crew_member_id = $1
ORDER BY t.embark_date ASC
`

type GetCrewMemberTripsRow struct {
	ID            int64             `json:"id"`
	OwnerID       int64             `json:"owner_id"`
	OrgID         types.NullInt64   `json:"org_id"`
	Name          string            `json:"name"`
	EmbarkDate    types.NullString  `json:"embark_date"`
	DisembarkDate types.NullString  `json:"disembark_date"`
	Countries     types.NullString  `json:"countries"`
	StartPort     types.NullString  `json:"start_port"`
	EndPort       types.NullString  `json:"end_port"`
	CaptainName   types.NullString  `json:"captain_name"`
	YachtID       types.NullInt64   `json:"yacht_id"`
	CostTotal     types.NullFloat64 `json:"cost_total"`
	CostPerPerson types.NullFloat64 `json:"cost_per_person"`
	MaxCrew       types.NullInt64   `json:"max_crew"`
	ImageLogoUrl  types.NullString  `json:"image_logo_url"`
	ImagePhotoUrl types.NullString  `json:"image_photo_url"`
	ImageRouteUrl types.NullString  `json:"image_route_url"`
	Description   types.NullString  `json:"description"`
	Status        TripStatus        `json:"status"`
	EnrollToken   types.NullString  `json:"enroll_token"`
	CreatedAt     types.NullTime    `json:"created_at"`
	UpdatedAt     types.NullTime    `json:"updated_at"`
	CruiseID      types.NullInt64   `json:"cruise_id"`
	Role          string            `json:"role"`
}

// GetCrewMemberTrips
//
//	SELECT t.id, t.owner_id, t.org_id, t.name, t.embark_date, t.disembark_date, t.countries, t.start_port, t.end_port, t.captain_name, t.yacht_id, t.cost_total, t.cost_per_person, t.max_crew, t.image_logo_url, t.image_photo_url, t.image_route_url, t.description, t.status, t.enroll_token, t.created_at, t.updated_at, t.cruise_id, ca.role
//	FROM crew_assignments ca
//	JOIN trips t ON t.id = ca.trip_id
//	WHERE ca.crew_member_id = $1
//	ORDER BY t.embark_date ASC
func (q *Queries) GetCrewMemberTrips(ctx context.Context, crewMemberID int64) ([]GetCrewMemberTripsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCrewMemberTrips, crewMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCrewMemberTripsRow
	for rows.Next() {
		var i GetCrewMemberTripsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.OrgID,
			&i.Name,
			&i.EmbarkDate,
			&i.DisembarkDate,
			&i.Countries,
			&i.StartPort,
			&i.EndPort,
			&i.CaptainName,
			&i.YachtID,
			&i.CostTotal,
			&i.CostPerPerson,
			&i.MaxCrew,
			&i.ImageLogoUrl,
			&i.ImagePhotoUrl,
			&i.ImageRouteUrl,
			&i.Description,
			&i.Status,
			&i.EnrollToken,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CruiseID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCrewMemberVoyages = `-- name: GetCrewMemberVoyages :many
SELECT v.id, v.owner_id, v.org_id, v.name, v.year, v.embark_date, v.disembark_date, v.countries, v.start_port, v.end_port, v.captain_name, v.yacht_id, v.hours_total, v.hours_sail, v.hours_engine, v.hours_over_6bf, v.miles, v.days, v.tidal_waters, v.cost_total, v.cost_per_person, v.image_logo_url, v.image_photo_url, v.image_route_url, v.description, v.created_at, v.updated_at, v.cruise_id, ca.role
FROM crew_assignments ca
JOIN voyages v ON v.id = ca.voyage_id
WHERE ca.crew_member_id = $1
ORDER BY v.year DESC, v.embark_date DESC
`

type GetCrewMemberVoyagesRow struct {
	ID            int64             `json:"id"`
	OwnerID       int64             `json:"owner_id"`
	OrgID         types.NullInt64   `json:"org_id"`
	Name          string            `json:"name"`
	Year          types.NullInt64   `json:"year"`
	EmbarkDate    types.NullString  `json:"embark_date"`
	DisembarkDate types.NullString  `json:"disembark_date"`
	Countries     types.NullString  `json:"countries"`
	StartPort     types.NullString  `json:"start_port"`
	EndPort       types.NullString  `json:"end_port"`
	CaptainName   types.NullString  `json:"captain_name"`
	YachtID       types.NullInt64   `json:"yacht_id"`
	HoursTotal    float64           `json:"hours_total"`
	HoursSail     float64           `json:"hours_sail"`
	HoursEngine   float64           `json:"hours_engine"`
	HoursOver6bf  float64           `json:"hours_over_6bf"`
	Miles         float64           `json:"miles"`
	Days          int64             `json:"days"`
	TidalWaters   int64             `json:"tidal_waters"`
	CostTotal     types.NullFloat64 `json:"cost_total"`
	CostPerPerson types.NullFloat64 `json:"cost_per_person"`
	ImageLogoUrl  types.NullString  `json:"image_logo_url"`
	ImagePhotoUrl types.NullString  `json:"image_photo_url"`
	ImageRouteUrl types.NullString  `json:"image_route_url"`
	Description   types.NullString  `json:"description"`
	CreatedAt     types.NullTime    `json:"created_at"`
	UpdatedAt     types.NullTime    `json:"updated_at"`
	CruiseID      types.NullInt64   `json:"cruise_id"`
	Role          string            `json:"role"`
}

// GetCrewMemberVoyages
//
//	SELECT v.id, v.owner_id, v.org_id, v.name, v.year, v.embark_date, v.disembark_date, v.countries, v.start_port, v.end_port, v.captain_name, v.yacht_id, v.hours_total, v.hours_sail, v.hours_engine, v.hours_over_6bf, v.miles, v.days, v.tidal_waters, v.cost_total, v.cost_per_person, v.image_logo_url, v.image_photo_url, v.image_route_url, v.description, v.created_at, v.updated_at, v.cruise_id, ca.role
//	FROM crew_assignments ca
//	JOIN voyages v ON v.id = ca.voyage_id
//	WHERE ca.crew_member_id = $1
//	ORDER BY v.year DESC, v.embark_date DESC
func (q *Queries) GetCrewMemberVoyages(ctx context.Context, crewMemberID int64) ([]GetCrewMemberVoyagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCrewMemberVoyages, crewMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCrewMemberVoyagesRow
	for rows.Next() {
		var i GetCrewMemberVoyagesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.OrgID,
			&i.Name,
			&i.Year,
			&i.EmbarkDate,
			&i.DisembarkDate,
			&i.Countries,
			&i.StartPort,
			&i.EndPort,
			&i.CaptainName,
			&i.YachtID,
			&i.HoursTotal,
			&i.HoursSail,
			&i.HoursEngine,
			&i.HoursOver6bf,
			&i.Miles,
			&i.Days,
			&i.TidalWaters,
			&i.CostTotal,
			&i.CostPerPerson,
			&i.ImageLogoUrl,
			&i.ImagePhotoUrl,
			&i.ImageRouteUrl,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CruiseID,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoyageCrewAssignmentByMember = `-- name: GetVoyageCrewAssignmentByMember :one
SELECT ca.id, ca.crew_member_id, ca.role, ca.patent_number, ca.created_at, ca.trip_id, ca.voyage_id, cm.full_name, cm.patent_number AS member_patent
FROM crew_assignments ca
JOIN crew_members cm ON cm.id = ca.crew_member_id
WHERE ca.voyage_id = $1 AND ca.crew_member_id = $2
`

type GetVoyageCrewAssignmentByMemberParams struct {
	VoyageID     types.NullInt64 `json:"voyage_id"`
	CrewMemberID int64           `json:"crew_member_id"`
}

type GetVoyageCrewAssignmentByMemberRow struct {
	ID           int64            `json:"id"`
	CrewMemberID int64            `json:"crew_member_id"`
	Role         string           `json:"role"`
	PatentNumber types.NullString `json:"patent_number"`
	CreatedAt    types.NullTime   `json:"created_at"`
	TripID       types.NullInt64  `json:"trip_id"`
	VoyageID     types.NullInt64  `json:"voyage_id"`
	FullName     string           `json:"full_name"`
	MemberPatent types.NullString `json:"member_patent"`
}

// GetVoyageCrewAssignmentByMember
//
//	SELECT ca.id, ca.crew_member_id, ca.role, ca.patent_number, ca.created_at, ca.trip_id, ca.voyage_id, cm.full_name, cm.patent_number AS member_patent
//	FROM crew_assignments ca
//	JOIN crew_members cm ON cm.id = ca.crew_member_id
//	WHERE ca.voyage_id = $1 AND ca.crew_member_id = $2
func (q *Queries) GetVoyageCrewAssignmentByMember(ctx context.Context, arg GetVoyageCrewAssignmentByMemberParams) (GetVoyageCrewAssignmentByMemberRow, error) {
	row := q.db.QueryRowContext(ctx, getVoyageCrewAssignmentByMember, arg.VoyageID, arg.CrewMemberID)
	var i GetVoyageCrewAssignmentByMemberRow
	err := row.Scan(
		&i.ID,
		&i.CrewMemberID,
		&i.Role,
		&i.PatentNumber,
		&i.CreatedAt,
		&i.TripID,
		&i.VoyageID,
		&i.FullName,
		&i.MemberPatent,
	)
	return i, err
}

const listTripCrewAssignments = `-- name: ListTripCrewAssignments :many
SELECT ca.id, ca.trip_id, ca.voyage_id, ca.crew_member_id, ca.role, ca.patent_number, ca.created_at,
       cm.full_name, cm.email
FROM crew_assignments ca
JOIN crew_members cm ON cm.id = ca.crew_member_id
JOIN trips t ON t.id = ca.trip_id
WHERE ca.trip_id = $1 AND t.owner_id = $2
ORDER BY cm.full_name
`

type ListTripCrewAssignmentsParams struct {
	TripID  types.NullInt64 `json:"trip_id"`
	OwnerID int64           `json:"owner_id"`
}

type ListTripCrewAssignmentsRow struct {
	ID           int64            `json:"id"`
	TripID       types.NullInt64  `json:"trip_id"`
	VoyageID     types.NullInt64  `json:"voyage_id"`
	CrewMemberID int64            `json:"crew_member_id"`
	Role         string           `json:"role"`
	PatentNumber types.NullString `json:"patent_number"`
	CreatedAt    types.NullTime   `json:"created_at"`
	FullName     string           `json:"full_name"`
	Email        types.NullString `json:"email"`
}

// ListTripCrewAssignments
//
//	SELECT ca.id, ca.trip_id, ca.voyage_id, ca.crew_member_id, ca.role, ca.patent_number, ca.created_at,
//	       cm.full_name, cm.email
//	FROM crew_assignments ca
//	JOIN crew_members cm ON cm.id = ca.crew_member_id
//	JOIN trips t ON t.id = ca.trip_id
//	WHERE ca.trip_id = $1 AND t.owner_id = $2
//	ORDER BY cm.full_name
func (q *Queries) ListTripCrewAssignments(ctx context.Context, arg ListTripCrewAssignmentsParams) ([]ListTripCrewAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTripCrewAssignments, arg.TripID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTripCrewAssignmentsRow
	for rows.Next() {
		var i ListTripCrewAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.VoyageID,
			&i.CrewMemberID,
			&i.Role,
			&i.PatentNumber,
			&i.CreatedAt,
			&i.FullName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoyageCrewAssignments = `-- name: ListVoyageCrewAssignments :many
SELECT ca.id, ca.trip_id, ca.voyage_id, ca.crew_member_id, ca.role, ca.patent_number, ca.created_at,
       cm.full_name, cm.email
FROM crew_assignments ca
JOIN crew_members cm ON cm.id = ca.crew_member_id
JOIN voyages v ON v.id = ca.voyage_id
WHERE ca.voyage_id = $1 AND v.owner_id = $2
ORDER BY cm.full_name
`

type ListVoyageCrewAssignmentsParams struct {
	VoyageID types.NullInt64 `json:"voyage_id"`
	OwnerID  int64           `json:"owner_id"`
}

type ListVoyageCrewAssignmentsRow struct {
	ID           int64            `json:"id"`
	TripID       types.NullInt64  `json:"trip_id"`
	VoyageID     types.NullInt64  `json:"voyage_id"`
	CrewMemberID int64            `json:"crew_member_id"`
	Role         string           `json:"role"`
	PatentNumber types.NullString `json:"patent_number"`
	CreatedAt    types.NullTime   `json:"created_at"`
	FullName     string           `json:"full_name"`
	Email        types.NullString `json:"email"`
}

// ListVoyageCrewAssignments
//
//	SELECT ca.id, ca.trip_id, ca.voyage_id, ca.crew_member_id, ca.role, ca.patent_number, ca.created_at,
//	       cm.full_name, cm.email
//	FROM crew_assignments ca
//	JOIN crew_members cm ON cm.id = ca.crew_member_id
//	JOIN voyages v ON v.id = ca.voyage_id
//	WHERE ca.voyage_id = $1 AND v.owner_id = $2
//	ORDER BY cm.full_name
func (q *Queries) ListVoyageCrewAssignments(ctx context.Context, arg ListVoyageCrewAssignmentsParams) ([]ListVoyageCrewAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVoyageCrewAssignments, arg.VoyageID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVoyageCrewAssignmentsRow
	for rows.Next() {
		var i ListVoyageCrewAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.VoyageID,
			&i.CrewMemberID,
			&i.Role,
			&i.PatentNumber,
			&i.CreatedAt,
			&i.FullName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repointCrewAssignmentsToVoyage = `-- name: RepointCrewAssignmentsToVoyage :exec
UPDATE crew_assignments SET voyage_id = $1, trip_id = NULL
WHERE trip_id = $2
`

type RepointCrewAssignmentsToVoyageParams struct {
	VoyageID types.NullInt64 `json:"voyage_id"`
	TripID   types.NullInt64 `json:"trip_id"`
}

// RepointCrewAssignmentsToVoyage
//
//	UPDATE crew_assignments SET voyage_id = $1, trip_id = NULL
//	WHERE trip_id = $2
func (q *Queries) RepointCrewAssignmentsToVoyage(ctx context.Context, arg RepointCrewAssignmentsToVoyageParams) error {
	_, err := q.db.ExecContext(ctx, repointCrewAssignmentsToVoyage, arg.VoyageID, arg.TripID)
	return err
}
