// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: crew_assignments.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const createCrewAssignment = `-- name: CreateCrewAssignment :one
INSERT INTO crew_assignments (cruise_id, crew_member_id, role, patent_number) VALUES ($1, $2, $3, $4) RETURNING id, cruise_id, crew_member_id, role, patent_number, created_at
`

type CreateCrewAssignmentParams struct {
	CruiseID     int64
	CrewMemberID int64
	Role         string
	PatentNumber sql.NullString
}

func (q *Queries) CreateCrewAssignment(ctx context.Context, arg CreateCrewAssignmentParams) (CrewAssignment, error) {
	row := q.db.QueryRowContext(ctx, createCrewAssignment,
		arg.CruiseID,
		arg.CrewMemberID,
		arg.Role,
		arg.PatentNumber,
	)
	var i CrewAssignment
	err := row.Scan(
		&i.ID,
		&i.CruiseID,
		&i.CrewMemberID,
		&i.Role,
		&i.PatentNumber,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCrewAssignment = `-- name: DeleteCrewAssignment :exec
DELETE FROM crew_assignments WHERE id = $1
`

func (q *Queries) DeleteCrewAssignment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCrewAssignment, id)
	return err
}

const getCrewMemberCruises = `-- name: GetCrewMemberCruises :many
SELECT c.id, c.owner_id, c.name, c.year, c.embark_date, c.disembark_date, c.countries, c.start_port, c.end_port, c.hours_total, c.hours_sail, c.hours_engine, c.hours_over_6bf, c.miles, c.days, c.captain_name, c.yacht_id, c.tidal_waters, c.cost_total, c.cost_per_person, c.image_logo_url, c.image_photo_url, c.image_route_url, c.description, c.created_at, c.updated_at, ca.role
FROM crew_assignments ca
JOIN cruises c ON c.id = ca.cruise_id
WHERE ca.crew_member_id = $1
ORDER BY c.year DESC, c.embark_date DESC
`

type GetCrewMemberCruisesRow struct {
	ID            int64
	OwnerID       int64
	Name          string
	Year          sql.NullInt64
	EmbarkDate    sql.NullString
	DisembarkDate sql.NullString
	Countries     sql.NullString
	StartPort     sql.NullString
	EndPort       sql.NullString
	HoursTotal    sql.NullFloat64
	HoursSail     sql.NullFloat64
	HoursEngine   sql.NullFloat64
	HoursOver6bf  sql.NullFloat64
	Miles         sql.NullFloat64
	Days          sql.NullInt64
	CaptainName   sql.NullString
	YachtID       sql.NullInt64
	TidalWaters   sql.NullInt64
	CostTotal     sql.NullFloat64
	CostPerPerson sql.NullFloat64
	ImageLogoUrl  sql.NullString
	ImagePhotoUrl sql.NullString
	ImageRouteUrl sql.NullString
	Description   sql.NullString
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	Role          string
}

func (q *Queries) GetCrewMemberCruises(ctx context.Context, crewMemberID int64) ([]GetCrewMemberCruisesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCrewMemberCruises, crewMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCrewMemberCruisesRow
	for rows.Next() {
		var i GetCrewMemberCruisesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Year,
			&i.EmbarkDate,
			&i.DisembarkDate,
			&i.Countries,
			&i.StartPort,
			&i.EndPort,
			&i.HoursTotal,
			&i.HoursSail,
			&i.HoursEngine,
			&i.HoursOver6bf,
			&i.Miles,
			&i.Days,
			&i.CaptainName,
			&i.YachtID,
			&i.TidalWaters,
			&i.CostTotal,
			&i.CostPerPerson,
			&i.ImageLogoUrl,
			&i.ImagePhotoUrl,
			&i.ImageRouteUrl,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCrewMemberStats = `-- name: GetCrewMemberStats :one
SELECT
    COUNT(*)::BIGINT AS cruise_count,
    COALESCE(SUM(c.hours_total), 0)::DOUBLE PRECISION AS total_hours,
    COALESCE(SUM(c.miles), 0)::DOUBLE PRECISION AS total_miles,
    COALESCE(SUM(c.days), 0)::BIGINT AS total_days
FROM crew_assignments ca
JOIN cruises c ON c.id = ca.cruise_id
WHERE ca.crew_member_id = $1
`

type GetCrewMemberStatsRow struct {
	CruiseCount int64
	TotalHours  float64
	TotalMiles  float64
	TotalDays   int64
}

func (q *Queries) GetCrewMemberStats(ctx context.Context, crewMemberID int64) (GetCrewMemberStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getCrewMemberStats, crewMemberID)
	var i GetCrewMemberStatsRow
	err := row.Scan(
		&i.CruiseCount,
		&i.TotalHours,
		&i.TotalMiles,
		&i.TotalDays,
	)
	return i, err
}

const listCruiseCrewAssignments = `-- name: ListCruiseCrewAssignments :many
SELECT ca.id, ca.cruise_id, ca.crew_member_id, ca.role, ca.patent_number, ca.created_at, cm.full_name, cm.email
FROM crew_assignments ca
JOIN crew_members cm ON cm.id = ca.crew_member_id
WHERE ca.cruise_id = $1
ORDER BY cm.full_name
`

type ListCruiseCrewAssignmentsRow struct {
	ID           int64
	CruiseID     int64
	CrewMemberID int64
	Role         string
	PatentNumber sql.NullString
	CreatedAt    sql.NullTime
	FullName     string
	Email        sql.NullString
}

func (q *Queries) ListCruiseCrewAssignments(ctx context.Context, cruiseID int64) ([]ListCruiseCrewAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCruiseCrewAssignments, cruiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCruiseCrewAssignmentsRow
	for rows.Next() {
		var i ListCruiseCrewAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CruiseID,
			&i.CrewMemberID,
			&i.Role,
			&i.PatentNumber,
			&i.CreatedAt,
			&i.FullName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
