// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cruises.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const cancelCruise = `-- name: CancelCruise :one
UPDATE cruises SET status = 'cancelled', enroll_token = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND owner_id = $2 AND org_id IS NULL AND status = 'planned' RETURNING id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status
`

type CancelCruiseParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) CancelCruise(ctx context.Context, arg CancelCruiseParams) (Cruise, error) {
	row := q.db.QueryRowContext(ctx, cancelCruise, arg.ID, arg.OwnerID)
	var i Cruise
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Year,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.HoursTotal,
		&i.HoursSail,
		&i.HoursEngine,
		&i.HoursOver6bf,
		&i.Miles,
		&i.Days,
		&i.CaptainName,
		&i.YachtID,
		&i.TidalWaters,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrollToken,
		&i.MaxCrew,
		&i.OrgID,
		&i.Status,
	)
	return i, err
}

const cancelOrgCruise = `-- name: CancelOrgCruise :one
UPDATE cruises SET status = 'cancelled', enroll_token = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND org_id = $2 AND status = 'planned' RETURNING id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status
`

type CancelOrgCruiseParams struct {
	ID    int64         `json:"id"`
	OrgID sql.NullInt64 `json:"org_id"`
}

func (q *Queries) CancelOrgCruise(ctx context.Context, arg CancelOrgCruiseParams) (Cruise, error) {
	row := q.db.QueryRowContext(ctx, cancelOrgCruise, arg.ID, arg.OrgID)
	var i Cruise
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Year,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.HoursTotal,
		&i.HoursSail,
		&i.HoursEngine,
		&i.HoursOver6bf,
		&i.Miles,
		&i.Days,
		&i.CaptainName,
		&i.YachtID,
		&i.TidalWaters,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrollToken,
		&i.MaxCrew,
		&i.OrgID,
		&i.Status,
	)
	return i, err
}

const clearCruiseEnrollToken = `-- name: ClearCruiseEnrollToken :exec
UPDATE cruises SET enroll_token = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND owner_id = $2
`

type ClearCruiseEnrollTokenParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) ClearCruiseEnrollToken(ctx context.Context, arg ClearCruiseEnrollTokenParams) error {
	_, err := q.db.ExecContext(ctx, clearCruiseEnrollToken, arg.ID, arg.OwnerID)
	return err
}

const completeCruise = `-- name: CompleteCruise :one
UPDATE cruises SET status = 'completed', enroll_token = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND owner_id = $2 AND org_id IS NULL AND status = 'planned' RETURNING id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status
`

type CompleteCruiseParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) CompleteCruise(ctx context.Context, arg CompleteCruiseParams) (Cruise, error) {
	row := q.db.QueryRowContext(ctx, completeCruise, arg.ID, arg.OwnerID)
	var i Cruise
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Year,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.HoursTotal,
		&i.HoursSail,
		&i.HoursEngine,
		&i.HoursOver6bf,
		&i.Miles,
		&i.Days,
		&i.CaptainName,
		&i.YachtID,
		&i.TidalWaters,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrollToken,
		&i.MaxCrew,
		&i.OrgID,
		&i.Status,
	)
	return i, err
}

const completeOrgCruise = `-- name: CompleteOrgCruise :one
UPDATE cruises SET status = 'completed', enroll_token = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND org_id = $2 AND status = 'planned' RETURNING id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status
`

type CompleteOrgCruiseParams struct {
	ID    int64         `json:"id"`
	OrgID sql.NullInt64 `json:"org_id"`
}

func (q *Queries) CompleteOrgCruise(ctx context.Context, arg CompleteOrgCruiseParams) (Cruise, error) {
	row := q.db.QueryRowContext(ctx, completeOrgCruise, arg.ID, arg.OrgID)
	var i Cruise
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Year,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.HoursTotal,
		&i.HoursSail,
		&i.HoursEngine,
		&i.HoursOver6bf,
		&i.Miles,
		&i.Days,
		&i.CaptainName,
		&i.YachtID,
		&i.TidalWaters,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrollToken,
		&i.MaxCrew,
		&i.OrgID,
		&i.Status,
	)
	return i, err
}

const createCruise = `-- name: CreateCruise :one
INSERT INTO cruises (
    owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port,
    hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days,
    captain_name, yacht_id, tidal_waters, cost_total, cost_per_person,
    image_logo_url, image_photo_url, image_route_url, description, max_crew, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25) RETURNING id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status
`

type CreateCruiseParams struct {
	OwnerID       int64           `json:"owner_id"`
	Name          string          `json:"name"`
	Year          sql.NullInt64   `json:"year"`
	EmbarkDate    sql.NullString  `json:"embark_date"`
	DisembarkDate sql.NullString  `json:"disembark_date"`
	Countries     sql.NullString  `json:"countries"`
	StartPort     sql.NullString  `json:"start_port"`
	EndPort       sql.NullString  `json:"end_port"`
	HoursTotal    sql.NullFloat64 `json:"hours_total"`
	HoursSail     sql.NullFloat64 `json:"hours_sail"`
	HoursEngine   sql.NullFloat64 `json:"hours_engine"`
	HoursOver6bf  sql.NullFloat64 `json:"hours_over_6bf"`
	Miles         sql.NullFloat64 `json:"miles"`
	Days          sql.NullInt64   `json:"days"`
	CaptainName   sql.NullString  `json:"captain_name"`
	YachtID       sql.NullInt64   `json:"yacht_id"`
	TidalWaters   sql.NullInt64   `json:"tidal_waters"`
	CostTotal     sql.NullFloat64 `json:"cost_total"`
	CostPerPerson sql.NullFloat64 `json:"cost_per_person"`
	ImageLogoUrl  sql.NullString  `json:"image_logo_url"`
	ImagePhotoUrl sql.NullString  `json:"image_photo_url"`
	ImageRouteUrl sql.NullString  `json:"image_route_url"`
	Description   sql.NullString  `json:"description"`
	MaxCrew       sql.NullInt64   `json:"max_crew"`
	Status        CruiseStatus    `json:"status"`
}

func (q *Queries) CreateCruise(ctx context.Context, arg CreateCruiseParams) (Cruise, error) {
	row := q.db.QueryRowContext(ctx, createCruise,
		arg.OwnerID,
		arg.Name,
		arg.Year,
		arg.EmbarkDate,
		arg.DisembarkDate,
		arg.Countries,
		arg.StartPort,
		arg.EndPort,
		arg.HoursTotal,
		arg.HoursSail,
		arg.HoursEngine,
		arg.HoursOver6bf,
		arg.Miles,
		arg.Days,
		arg.CaptainName,
		arg.YachtID,
		arg.TidalWaters,
		arg.CostTotal,
		arg.CostPerPerson,
		arg.ImageLogoUrl,
		arg.ImagePhotoUrl,
		arg.ImageRouteUrl,
		arg.Description,
		arg.MaxCrew,
		arg.Status,
	)
	var i Cruise
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Year,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.HoursTotal,
		&i.HoursSail,
		&i.HoursEngine,
		&i.HoursOver6bf,
		&i.Miles,
		&i.Days,
		&i.CaptainName,
		&i.YachtID,
		&i.TidalWaters,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrollToken,
		&i.MaxCrew,
		&i.OrgID,
		&i.Status,
	)
	return i, err
}

const createOrgCruise = `-- name: CreateOrgCruise :one
INSERT INTO cruises (
    owner_id, org_id, name, year, embark_date, disembark_date, countries, start_port, end_port,
    hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days,
    captain_name, yacht_id, tidal_waters, cost_total, cost_per_person,
    image_logo_url, image_photo_url, image_route_url, description, max_crew, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26) RETURNING id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status
`

type CreateOrgCruiseParams struct {
	OwnerID       int64           `json:"owner_id"`
	OrgID         sql.NullInt64   `json:"org_id"`
	Name          string          `json:"name"`
	Year          sql.NullInt64   `json:"year"`
	EmbarkDate    sql.NullString  `json:"embark_date"`
	DisembarkDate sql.NullString  `json:"disembark_date"`
	Countries     sql.NullString  `json:"countries"`
	StartPort     sql.NullString  `json:"start_port"`
	EndPort       sql.NullString  `json:"end_port"`
	HoursTotal    sql.NullFloat64 `json:"hours_total"`
	HoursSail     sql.NullFloat64 `json:"hours_sail"`
	HoursEngine   sql.NullFloat64 `json:"hours_engine"`
	HoursOver6bf  sql.NullFloat64 `json:"hours_over_6bf"`
	Miles         sql.NullFloat64 `json:"miles"`
	Days          sql.NullInt64   `json:"days"`
	CaptainName   sql.NullString  `json:"captain_name"`
	YachtID       sql.NullInt64   `json:"yacht_id"`
	TidalWaters   sql.NullInt64   `json:"tidal_waters"`
	CostTotal     sql.NullFloat64 `json:"cost_total"`
	CostPerPerson sql.NullFloat64 `json:"cost_per_person"`
	ImageLogoUrl  sql.NullString  `json:"image_logo_url"`
	ImagePhotoUrl sql.NullString  `json:"image_photo_url"`
	ImageRouteUrl sql.NullString  `json:"image_route_url"`
	Description   sql.NullString  `json:"description"`
	MaxCrew       sql.NullInt64   `json:"max_crew"`
	Status        CruiseStatus    `json:"status"`
}

func (q *Queries) CreateOrgCruise(ctx context.Context, arg CreateOrgCruiseParams) (Cruise, error) {
	row := q.db.QueryRowContext(ctx, createOrgCruise,
		arg.OwnerID,
		arg.OrgID,
		arg.Name,
		arg.Year,
		arg.EmbarkDate,
		arg.DisembarkDate,
		arg.Countries,
		arg.StartPort,
		arg.EndPort,
		arg.HoursTotal,
		arg.HoursSail,
		arg.HoursEngine,
		arg.HoursOver6bf,
		arg.Miles,
		arg.Days,
		arg.CaptainName,
		arg.YachtID,
		arg.TidalWaters,
		arg.CostTotal,
		arg.CostPerPerson,
		arg.ImageLogoUrl,
		arg.ImagePhotoUrl,
		arg.ImageRouteUrl,
		arg.Description,
		arg.MaxCrew,
		arg.Status,
	)
	var i Cruise
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Year,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.HoursTotal,
		&i.HoursSail,
		&i.HoursEngine,
		&i.HoursOver6bf,
		&i.Miles,
		&i.Days,
		&i.CaptainName,
		&i.YachtID,
		&i.TidalWaters,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrollToken,
		&i.MaxCrew,
		&i.OrgID,
		&i.Status,
	)
	return i, err
}

const deleteCruise = `-- name: DeleteCruise :exec
DELETE FROM cruises WHERE id = $1 AND owner_id = $2 AND org_id IS NULL
`

type DeleteCruiseParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) DeleteCruise(ctx context.Context, arg DeleteCruiseParams) error {
	_, err := q.db.ExecContext(ctx, deleteCruise, arg.ID, arg.OwnerID)
	return err
}

const deleteOrgCruise = `-- name: DeleteOrgCruise :exec
DELETE FROM cruises WHERE id = $1 AND org_id = $2
`

type DeleteOrgCruiseParams struct {
	ID    int64         `json:"id"`
	OrgID sql.NullInt64 `json:"org_id"`
}

func (q *Queries) DeleteOrgCruise(ctx context.Context, arg DeleteOrgCruiseParams) error {
	_, err := q.db.ExecContext(ctx, deleteOrgCruise, arg.ID, arg.OrgID)
	return err
}

const getCruise = `-- name: GetCruise :one
SELECT id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status FROM cruises WHERE id = $1 AND owner_id = $2 AND org_id IS NULL
`

type GetCruiseParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) GetCruise(ctx context.Context, arg GetCruiseParams) (Cruise, error) {
	row := q.db.QueryRowContext(ctx, getCruise, arg.ID, arg.OwnerID)
	var i Cruise
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Year,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.HoursTotal,
		&i.HoursSail,
		&i.HoursEngine,
		&i.HoursOver6bf,
		&i.Miles,
		&i.Days,
		&i.CaptainName,
		&i.YachtID,
		&i.TidalWaters,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrollToken,
		&i.MaxCrew,
		&i.OrgID,
		&i.Status,
	)
	return i, err
}

const getCruiseStatus = `-- name: GetCruiseStatus :one
SELECT status FROM cruises WHERE id = $1
`

func (q *Queries) GetCruiseStatus(ctx context.Context, id int64) (CruiseStatus, error) {
	row := q.db.QueryRowContext(ctx, getCruiseStatus, id)
	var status CruiseStatus
	err := row.Scan(&status)
	return status, err
}

const getCruisesByYear = `-- name: GetCruisesByYear :many
SELECT
    year,
    COUNT(*)::BIGINT AS cruise_count,
    COALESCE(SUM(hours_total), 0)::DOUBLE PRECISION AS total_hours,
    COALESCE(SUM(miles), 0)::DOUBLE PRECISION AS total_miles,
    COALESCE(SUM(days), 0)::BIGINT AS total_days
FROM cruises WHERE owner_id = $1 AND org_id IS NULL AND status = 'completed' GROUP BY year ORDER BY year
`

type GetCruisesByYearRow struct {
	Year        sql.NullInt64 `json:"year"`
	CruiseCount int64         `json:"cruise_count"`
	TotalHours  float64       `json:"total_hours"`
	TotalMiles  float64       `json:"total_miles"`
	TotalDays   int64         `json:"total_days"`
}

func (q *Queries) GetCruisesByYear(ctx context.Context, ownerID int64) ([]GetCruisesByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, getCruisesByYear, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCruisesByYearRow
	for rows.Next() {
		var i GetCruisesByYearRow
		if err := rows.Scan(
			&i.Year,
			&i.CruiseCount,
			&i.TotalHours,
			&i.TotalMiles,
			&i.TotalDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    COUNT(*)::BIGINT AS cruise_count,
    COALESCE(SUM(hours_total), 0)::DOUBLE PRECISION AS total_hours,
    COALESCE(SUM(miles), 0)::DOUBLE PRECISION AS total_miles,
    COALESCE(SUM(days), 0)::BIGINT AS total_days,
    COALESCE(SUM(hours_sail), 0)::DOUBLE PRECISION AS total_hours_sail,
    COALESCE(SUM(hours_engine), 0)::DOUBLE PRECISION AS total_hours_engine
FROM cruises WHERE owner_id = $1 AND org_id IS NULL AND status = 'completed'
`

type GetDashboardStatsRow struct {
	CruiseCount      int64   `json:"cruise_count"`
	TotalHours       float64 `json:"total_hours"`
	TotalMiles       float64 `json:"total_miles"`
	TotalDays        int64   `json:"total_days"`
	TotalHoursSail   float64 `json:"total_hours_sail"`
	TotalHoursEngine float64 `json:"total_hours_engine"`
}

func (q *Queries) GetDashboardStats(ctx context.Context, ownerID int64) (GetDashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardStats, ownerID)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.CruiseCount,
		&i.TotalHours,
		&i.TotalMiles,
		&i.TotalDays,
		&i.TotalHoursSail,
		&i.TotalHoursEngine,
	)
	return i, err
}

const getOrgCruise = `-- name: GetOrgCruise :one
SELECT id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status FROM cruises WHERE id = $1 AND org_id = $2
`

type GetOrgCruiseParams struct {
	ID    int64         `json:"id"`
	OrgID sql.NullInt64 `json:"org_id"`
}

func (q *Queries) GetOrgCruise(ctx context.Context, arg GetOrgCruiseParams) (Cruise, error) {
	row := q.db.QueryRowContext(ctx, getOrgCruise, arg.ID, arg.OrgID)
	var i Cruise
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Year,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.HoursTotal,
		&i.HoursSail,
		&i.HoursEngine,
		&i.HoursOver6bf,
		&i.Miles,
		&i.Days,
		&i.CaptainName,
		&i.YachtID,
		&i.TidalWaters,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrollToken,
		&i.MaxCrew,
		&i.OrgID,
		&i.Status,
	)
	return i, err
}

const getOrgCruisesByYear = `-- name: GetOrgCruisesByYear :many
SELECT
    year,
    COUNT(*)::BIGINT AS cruise_count,
    COALESCE(SUM(hours_total), 0)::DOUBLE PRECISION AS total_hours,
    COALESCE(SUM(miles), 0)::DOUBLE PRECISION AS total_miles,
    COALESCE(SUM(days), 0)::BIGINT AS total_days
FROM cruises WHERE org_id = $1 AND status = 'completed' GROUP BY year ORDER BY year
`

type GetOrgCruisesByYearRow struct {
	Year        sql.NullInt64 `json:"year"`
	CruiseCount int64         `json:"cruise_count"`
	TotalHours  float64       `json:"total_hours"`
	TotalMiles  float64       `json:"total_miles"`
	TotalDays   int64         `json:"total_days"`
}

func (q *Queries) GetOrgCruisesByYear(ctx context.Context, orgID sql.NullInt64) ([]GetOrgCruisesByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrgCruisesByYear, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrgCruisesByYearRow
	for rows.Next() {
		var i GetOrgCruisesByYearRow
		if err := rows.Scan(
			&i.Year,
			&i.CruiseCount,
			&i.TotalHours,
			&i.TotalMiles,
			&i.TotalDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrgDashboardStats = `-- name: GetOrgDashboardStats :one
SELECT
    COUNT(*)::BIGINT AS cruise_count,
    COALESCE(SUM(hours_total), 0)::DOUBLE PRECISION AS total_hours,
    COALESCE(SUM(miles), 0)::DOUBLE PRECISION AS total_miles,
    COALESCE(SUM(days), 0)::BIGINT AS total_days,
    COALESCE(SUM(hours_sail), 0)::DOUBLE PRECISION AS total_hours_sail,
    COALESCE(SUM(hours_engine), 0)::DOUBLE PRECISION AS total_hours_engine
FROM cruises WHERE org_id = $1 AND status = 'completed'
`

type GetOrgDashboardStatsRow struct {
	CruiseCount      int64   `json:"cruise_count"`
	TotalHours       float64 `json:"total_hours"`
	TotalMiles       float64 `json:"total_miles"`
	TotalDays        int64   `json:"total_days"`
	TotalHoursSail   float64 `json:"total_hours_sail"`
	TotalHoursEngine float64 `json:"total_hours_engine"`
}

func (q *Queries) GetOrgDashboardStats(ctx context.Context, orgID sql.NullInt64) (GetOrgDashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getOrgDashboardStats, orgID)
	var i GetOrgDashboardStatsRow
	err := row.Scan(
		&i.CruiseCount,
		&i.TotalHours,
		&i.TotalMiles,
		&i.TotalDays,
		&i.TotalHoursSail,
		&i.TotalHoursEngine,
	)
	return i, err
}

const listCruises = `-- name: ListCruises :many
SELECT id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status FROM cruises WHERE owner_id = $1 AND org_id IS NULL ORDER BY year DESC, embark_date DESC
`

func (q *Queries) ListCruises(ctx context.Context, ownerID int64) ([]Cruise, error) {
	rows, err := q.db.QueryContext(ctx, listCruises, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cruise
	for rows.Next() {
		var i Cruise
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Year,
			&i.EmbarkDate,
			&i.DisembarkDate,
			&i.Countries,
			&i.StartPort,
			&i.EndPort,
			&i.HoursTotal,
			&i.HoursSail,
			&i.HoursEngine,
			&i.HoursOver6bf,
			&i.Miles,
			&i.Days,
			&i.CaptainName,
			&i.YachtID,
			&i.TidalWaters,
			&i.CostTotal,
			&i.CostPerPerson,
			&i.ImageLogoUrl,
			&i.ImagePhotoUrl,
			&i.ImageRouteUrl,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrollToken,
			&i.MaxCrew,
			&i.OrgID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgCruises = `-- name: ListOrgCruises :many
SELECT id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status FROM cruises WHERE org_id = $1 ORDER BY year DESC, embark_date DESC
`

func (q *Queries) ListOrgCruises(ctx context.Context, orgID sql.NullInt64) ([]Cruise, error) {
	rows, err := q.db.QueryContext(ctx, listOrgCruises, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cruise
	for rows.Next() {
		var i Cruise
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Year,
			&i.EmbarkDate,
			&i.DisembarkDate,
			&i.Countries,
			&i.StartPort,
			&i.EndPort,
			&i.HoursTotal,
			&i.HoursSail,
			&i.HoursEngine,
			&i.HoursOver6bf,
			&i.Miles,
			&i.Days,
			&i.CaptainName,
			&i.YachtID,
			&i.TidalWaters,
			&i.CostTotal,
			&i.CostPerPerson,
			&i.ImageLogoUrl,
			&i.ImagePhotoUrl,
			&i.ImageRouteUrl,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrollToken,
			&i.MaxCrew,
			&i.OrgID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgTrips = `-- name: ListOrgTrips :many
SELECT id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status FROM cruises WHERE org_id = $1 AND status = 'planned' ORDER BY embark_date ASC
`

func (q *Queries) ListOrgTrips(ctx context.Context, orgID sql.NullInt64) ([]Cruise, error) {
	rows, err := q.db.QueryContext(ctx, listOrgTrips, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cruise
	for rows.Next() {
		var i Cruise
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Year,
			&i.EmbarkDate,
			&i.DisembarkDate,
			&i.Countries,
			&i.StartPort,
			&i.EndPort,
			&i.HoursTotal,
			&i.HoursSail,
			&i.HoursEngine,
			&i.HoursOver6bf,
			&i.Miles,
			&i.Days,
			&i.CaptainName,
			&i.YachtID,
			&i.TidalWaters,
			&i.CostTotal,
			&i.CostPerPerson,
			&i.ImageLogoUrl,
			&i.ImagePhotoUrl,
			&i.ImageRouteUrl,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrollToken,
			&i.MaxCrew,
			&i.OrgID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgVoyages = `-- name: ListOrgVoyages :many
SELECT id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status FROM cruises WHERE org_id = $1 AND status = 'completed' ORDER BY year DESC, embark_date DESC
`

func (q *Queries) ListOrgVoyages(ctx context.Context, orgID sql.NullInt64) ([]Cruise, error) {
	rows, err := q.db.QueryContext(ctx, listOrgVoyages, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cruise
	for rows.Next() {
		var i Cruise
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Year,
			&i.EmbarkDate,
			&i.DisembarkDate,
			&i.Countries,
			&i.StartPort,
			&i.EndPort,
			&i.HoursTotal,
			&i.HoursSail,
			&i.HoursEngine,
			&i.HoursOver6bf,
			&i.Miles,
			&i.Days,
			&i.CaptainName,
			&i.YachtID,
			&i.TidalWaters,
			&i.CostTotal,
			&i.CostPerPerson,
			&i.ImageLogoUrl,
			&i.ImagePhotoUrl,
			&i.ImageRouteUrl,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrollToken,
			&i.MaxCrew,
			&i.OrgID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrips = `-- name: ListTrips :many
SELECT id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status FROM cruises WHERE owner_id = $1 AND org_id IS NULL AND status = 'planned' ORDER BY embark_date ASC
`

func (q *Queries) ListTrips(ctx context.Context, ownerID int64) ([]Cruise, error) {
	rows, err := q.db.QueryContext(ctx, listTrips, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cruise
	for rows.Next() {
		var i Cruise
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Year,
			&i.EmbarkDate,
			&i.DisembarkDate,
			&i.Countries,
			&i.StartPort,
			&i.EndPort,
			&i.HoursTotal,
			&i.HoursSail,
			&i.HoursEngine,
			&i.HoursOver6bf,
			&i.Miles,
			&i.Days,
			&i.CaptainName,
			&i.YachtID,
			&i.TidalWaters,
			&i.CostTotal,
			&i.CostPerPerson,
			&i.ImageLogoUrl,
			&i.ImagePhotoUrl,
			&i.ImageRouteUrl,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrollToken,
			&i.MaxCrew,
			&i.OrgID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoyages = `-- name: ListVoyages :many
SELECT id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status FROM cruises WHERE owner_id = $1 AND org_id IS NULL AND status = 'completed' ORDER BY year DESC, embark_date DESC
`

func (q *Queries) ListVoyages(ctx context.Context, ownerID int64) ([]Cruise, error) {
	rows, err := q.db.QueryContext(ctx, listVoyages, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cruise
	for rows.Next() {
		var i Cruise
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Year,
			&i.EmbarkDate,
			&i.DisembarkDate,
			&i.Countries,
			&i.StartPort,
			&i.EndPort,
			&i.HoursTotal,
			&i.HoursSail,
			&i.HoursEngine,
			&i.HoursOver6bf,
			&i.Miles,
			&i.Days,
			&i.CaptainName,
			&i.YachtID,
			&i.TidalWaters,
			&i.CostTotal,
			&i.CostPerPerson,
			&i.ImageLogoUrl,
			&i.ImagePhotoUrl,
			&i.ImageRouteUrl,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrollToken,
			&i.MaxCrew,
			&i.OrgID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenCruise = `-- name: ReopenCruise :one
UPDATE cruises SET status = 'planned', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND owner_id = $2 AND org_id IS NULL AND status = 'completed' RETURNING id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status
`

type ReopenCruiseParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) ReopenCruise(ctx context.Context, arg ReopenCruiseParams) (Cruise, error) {
	row := q.db.QueryRowContext(ctx, reopenCruise, arg.ID, arg.OwnerID)
	var i Cruise
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Year,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.HoursTotal,
		&i.HoursSail,
		&i.HoursEngine,
		&i.HoursOver6bf,
		&i.Miles,
		&i.Days,
		&i.CaptainName,
		&i.YachtID,
		&i.TidalWaters,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrollToken,
		&i.MaxCrew,
		&i.OrgID,
		&i.Status,
	)
	return i, err
}

const reopenOrgCruise = `-- name: ReopenOrgCruise :one
UPDATE cruises SET status = 'planned', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND org_id = $2 AND status = 'completed' RETURNING id, owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, captain_name, yacht_id, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, enroll_token, max_crew, org_id, status
`

type ReopenOrgCruiseParams struct {
	ID    int64         `json:"id"`
	OrgID sql.NullInt64 `json:"org_id"`
}

func (q *Queries) ReopenOrgCruise(ctx context.Context, arg ReopenOrgCruiseParams) (Cruise, error) {
	row := q.db.QueryRowContext(ctx, reopenOrgCruise, arg.ID, arg.OrgID)
	var i Cruise
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Year,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.HoursTotal,
		&i.HoursSail,
		&i.HoursEngine,
		&i.HoursOver6bf,
		&i.Miles,
		&i.Days,
		&i.CaptainName,
		&i.YachtID,
		&i.TidalWaters,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EnrollToken,
		&i.MaxCrew,
		&i.OrgID,
		&i.Status,
	)
	return i, err
}

const setCruiseEnrollToken = `-- name: SetCruiseEnrollToken :exec
UPDATE cruises SET enroll_token = $1, updated_at = CURRENT_TIMESTAMP
WHERE id = $2 AND owner_id = $3
`

type SetCruiseEnrollTokenParams struct {
	EnrollToken sql.NullString `json:"enroll_token"`
	ID          int64          `json:"id"`
	OwnerID     int64          `json:"owner_id"`
}

func (q *Queries) SetCruiseEnrollToken(ctx context.Context, arg SetCruiseEnrollTokenParams) error {
	_, err := q.db.ExecContext(ctx, setCruiseEnrollToken, arg.EnrollToken, arg.ID, arg.OwnerID)
	return err
}

const updateCruise = `-- name: UpdateCruise :exec
UPDATE cruises SET
    name = $1, year = $2, embark_date = $3, disembark_date = $4, countries = $5,
    start_port = $6, end_port = $7, hours_total = $8, hours_sail = $9, hours_engine = $10,
    hours_over_6bf = $11, miles = $12, days = $13, captain_name = $14, yacht_id = $15,
    tidal_waters = $16, cost_total = $17, cost_per_person = $18,
    image_logo_url = $19, image_photo_url = $20, image_route_url = $21, description = $22,
    max_crew = $23, updated_at = CURRENT_TIMESTAMP
WHERE id = $24 AND owner_id = $25 AND org_id IS NULL
`

type UpdateCruiseParams struct {
	Name          string          `json:"name"`
	Year          sql.NullInt64   `json:"year"`
	EmbarkDate    sql.NullString  `json:"embark_date"`
	DisembarkDate sql.NullString  `json:"disembark_date"`
	Countries     sql.NullString  `json:"countries"`
	StartPort     sql.NullString  `json:"start_port"`
	EndPort       sql.NullString  `json:"end_port"`
	HoursTotal    sql.NullFloat64 `json:"hours_total"`
	HoursSail     sql.NullFloat64 `json:"hours_sail"`
	HoursEngine   sql.NullFloat64 `json:"hours_engine"`
	HoursOver6bf  sql.NullFloat64 `json:"hours_over_6bf"`
	Miles         sql.NullFloat64 `json:"miles"`
	Days          sql.NullInt64   `json:"days"`
	CaptainName   sql.NullString  `json:"captain_name"`
	YachtID       sql.NullInt64   `json:"yacht_id"`
	TidalWaters   sql.NullInt64   `json:"tidal_waters"`
	CostTotal     sql.NullFloat64 `json:"cost_total"`
	CostPerPerson sql.NullFloat64 `json:"cost_per_person"`
	ImageLogoUrl  sql.NullString  `json:"image_logo_url"`
	ImagePhotoUrl sql.NullString  `json:"image_photo_url"`
	ImageRouteUrl sql.NullString  `json:"image_route_url"`
	Description   sql.NullString  `json:"description"`
	MaxCrew       sql.NullInt64   `json:"max_crew"`
	ID            int64           `json:"id"`
	OwnerID       int64           `json:"owner_id"`
}

func (q *Queries) UpdateCruise(ctx context.Context, arg UpdateCruiseParams) error {
	_, err := q.db.ExecContext(ctx, updateCruise,
		arg.Name,
		arg.Year,
		arg.EmbarkDate,
		arg.DisembarkDate,
		arg.Countries,
		arg.StartPort,
		arg.EndPort,
		arg.HoursTotal,
		arg.HoursSail,
		arg.HoursEngine,
		arg.HoursOver6bf,
		arg.Miles,
		arg.Days,
		arg.CaptainName,
		arg.YachtID,
		arg.TidalWaters,
		arg.CostTotal,
		arg.CostPerPerson,
		arg.ImageLogoUrl,
		arg.ImagePhotoUrl,
		arg.ImageRouteUrl,
		arg.Description,
		arg.MaxCrew,
		arg.ID,
		arg.OwnerID,
	)
	return err
}

const updateOrgCruise = `-- name: UpdateOrgCruise :exec
UPDATE cruises SET
    name = $1, year = $2, embark_date = $3, disembark_date = $4, countries = $5,
    start_port = $6, end_port = $7, hours_total = $8, hours_sail = $9, hours_engine = $10,
    hours_over_6bf = $11, miles = $12, days = $13, captain_name = $14, yacht_id = $15,
    tidal_waters = $16, cost_total = $17, cost_per_person = $18,
    image_logo_url = $19, image_photo_url = $20, image_route_url = $21, description = $22,
    max_crew = $23, updated_at = CURRENT_TIMESTAMP
WHERE id = $24 AND org_id = $25
`

type UpdateOrgCruiseParams struct {
	Name          string          `json:"name"`
	Year          sql.NullInt64   `json:"year"`
	EmbarkDate    sql.NullString  `json:"embark_date"`
	DisembarkDate sql.NullString  `json:"disembark_date"`
	Countries     sql.NullString  `json:"countries"`
	StartPort     sql.NullString  `json:"start_port"`
	EndPort       sql.NullString  `json:"end_port"`
	HoursTotal    sql.NullFloat64 `json:"hours_total"`
	HoursSail     sql.NullFloat64 `json:"hours_sail"`
	HoursEngine   sql.NullFloat64 `json:"hours_engine"`
	HoursOver6bf  sql.NullFloat64 `json:"hours_over_6bf"`
	Miles         sql.NullFloat64 `json:"miles"`
	Days          sql.NullInt64   `json:"days"`
	CaptainName   sql.NullString  `json:"captain_name"`
	YachtID       sql.NullInt64   `json:"yacht_id"`
	TidalWaters   sql.NullInt64   `json:"tidal_waters"`
	CostTotal     sql.NullFloat64 `json:"cost_total"`
	CostPerPerson sql.NullFloat64 `json:"cost_per_person"`
	ImageLogoUrl  sql.NullString  `json:"image_logo_url"`
	ImagePhotoUrl sql.NullString  `json:"image_photo_url"`
	ImageRouteUrl sql.NullString  `json:"image_route_url"`
	Description   sql.NullString  `json:"description"`
	MaxCrew       sql.NullInt64   `json:"max_crew"`
	ID            int64           `json:"id"`
	OrgID         sql.NullInt64   `json:"org_id"`
}

func (q *Queries) UpdateOrgCruise(ctx context.Context, arg UpdateOrgCruiseParams) error {
	_, err := q.db.ExecContext(ctx, updateOrgCruise,
		arg.Name,
		arg.Year,
		arg.EmbarkDate,
		arg.DisembarkDate,
		arg.Countries,
		arg.StartPort,
		arg.EndPort,
		arg.HoursTotal,
		arg.HoursSail,
		arg.HoursEngine,
		arg.HoursOver6bf,
		arg.Miles,
		arg.Days,
		arg.CaptainName,
		arg.YachtID,
		arg.TidalWaters,
		arg.CostTotal,
		arg.CostPerPerson,
		arg.ImageLogoUrl,
		arg.ImagePhotoUrl,
		arg.ImageRouteUrl,
		arg.Description,
		arg.MaxCrew,
		arg.ID,
		arg.OrgID,
	)
	return err
}
