// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cruise_enrollments.sql

package sqlcdb

import (
	"context"

	types "github.com/marcinskalski/sailor-buddy/backend/internal/types"
)

const assignCruiseEnrollmentToTrip = `-- name: AssignCruiseEnrollmentToTrip :exec
UPDATE cruise_enrollments ce SET
    trip_id = $1,
    updated_at = CURRENT_TIMESTAMP
FROM cruises c
WHERE ce.id = $2 AND ce.cruise_id = c.id AND c.org_id = $3
  AND ($1::BIGINT IS NULL OR EXISTS (
      SELECT 1 FROM trips t WHERE t.id = $1 AND t.cruise_id = ce.cruise_id
  ))
`

type AssignCruiseEnrollmentToTripParams struct {
	TripID types.NullInt64 `json:"trip_id"`
	ID     int64           `json:"id"`
	OrgID  int64           `json:"org_id"`
}

func (q *Queries) AssignCruiseEnrollmentToTrip(ctx context.Context, arg AssignCruiseEnrollmentToTripParams) error {
	_, err := q.db.ExecContext(ctx, assignCruiseEnrollmentToTrip, arg.TripID, arg.ID, arg.OrgID)
	return err
}

const countCruiseEnrollments = `-- name: CountCruiseEnrollments :one
SELECT
    COUNT(*) FILTER (WHERE status = 'accepted')::BIGINT AS accepted,
    COUNT(*)::BIGINT AS total
FROM cruise_enrollments
WHERE cruise_id = $1
`

type CountCruiseEnrollmentsRow struct {
	Accepted int64 `json:"accepted"`
	Total    int64 `json:"total"`
}

func (q *Queries) CountCruiseEnrollments(ctx context.Context, cruiseID int64) (CountCruiseEnrollmentsRow, error) {
	row := q.db.QueryRowContext(ctx, countCruiseEnrollments, cruiseID)
	var i CountCruiseEnrollmentsRow
	err := row.Scan(&i.Accepted, &i.Total)
	return i, err
}

const createCruiseEnrollment = `-- name: CreateCruiseEnrollment :one
INSERT INTO cruise_enrollments (cruise_id, user_id, note)
VALUES ($1, $2, $3) RETURNING id, cruise_id, user_id, trip_id, note, status, created_at, updated_at
`

type CreateCruiseEnrollmentParams struct {
	CruiseID int64            `json:"cruise_id"`
	UserID   int64            `json:"user_id"`
	Note     types.NullString `json:"note"`
}

func (q *Queries) CreateCruiseEnrollment(ctx context.Context, arg CreateCruiseEnrollmentParams) (CruiseEnrollment, error) {
	row := q.db.QueryRowContext(ctx, createCruiseEnrollment, arg.CruiseID, arg.UserID, arg.Note)
	var i CruiseEnrollment
	err := row.Scan(
		&i.ID,
		&i.CruiseID,
		&i.UserID,
		&i.TripID,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCruiseEnrollment = `-- name: DeleteCruiseEnrollment :exec
DELETE FROM cruise_enrollments ce
USING cruises c
WHERE ce.id = $1 AND ce.cruise_id = c.id AND c.org_id = $2
`

type DeleteCruiseEnrollmentParams struct {
	ID    int64 `json:"id"`
	OrgID int64 `json:"org_id"`
}

func (q *Queries) DeleteCruiseEnrollment(ctx context.Context, arg DeleteCruiseEnrollmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteCruiseEnrollment, arg.ID, arg.OrgID)
	return err
}

const getUserCruiseEnrollment = `-- name: GetUserCruiseEnrollment :one
SELECT id, cruise_id, user_id, trip_id, note, status, created_at, updated_at FROM cruise_enrollments
WHERE cruise_id = $1 AND user_id = $2
`

type GetUserCruiseEnrollmentParams struct {
	CruiseID int64 `json:"cruise_id"`
	UserID   int64 `json:"user_id"`
}

func (q *Queries) GetUserCruiseEnrollment(ctx context.Context, arg GetUserCruiseEnrollmentParams) (CruiseEnrollment, error) {
	row := q.db.QueryRowContext(ctx, getUserCruiseEnrollment, arg.CruiseID, arg.UserID)
	var i CruiseEnrollment
	err := row.Scan(
		&i.ID,
		&i.CruiseID,
		&i.UserID,
		&i.TripID,
		&i.Note,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCruiseEnrollments = `-- name: ListCruiseEnrollments :many
SELECT ce.id, ce.cruise_id, ce.user_id, ce.trip_id, ce.note, ce.status, ce.created_at, ce.updated_at,
       u.name AS user_name, u.email AS user_email,
       t.name AS trip_name
FROM cruise_enrollments ce
JOIN users u ON u.id = ce.user_id
JOIN cruises c ON c.id = ce.cruise_id
LEFT JOIN trips t ON t.id = ce.trip_id
WHERE ce.cruise_id = $1 AND c.org_id = $2
ORDER BY ce.created_at
`

type ListCruiseEnrollmentsParams struct {
	CruiseID int64 `json:"cruise_id"`
	OrgID    int64 `json:"org_id"`
}

type ListCruiseEnrollmentsRow struct {
	ID        int64            `json:"id"`
	CruiseID  int64            `json:"cruise_id"`
	UserID    int64            `json:"user_id"`
	TripID    types.NullInt64  `json:"trip_id"`
	Note      types.NullString `json:"note"`
	Status    string           `json:"status"`
	CreatedAt types.NullTime   `json:"created_at"`
	UpdatedAt types.NullTime   `json:"updated_at"`
	UserName  string           `json:"user_name"`
	UserEmail string           `json:"user_email"`
	TripName  types.NullString `json:"trip_name"`
}

func (q *Queries) ListCruiseEnrollments(ctx context.Context, arg ListCruiseEnrollmentsParams) ([]ListCruiseEnrollmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCruiseEnrollments, arg.CruiseID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCruiseEnrollmentsRow
	for rows.Next() {
		var i ListCruiseEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CruiseID,
			&i.UserID,
			&i.TripID,
			&i.Note,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.TripName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCruiseEnrollmentStatus = `-- name: UpdateCruiseEnrollmentStatus :exec
UPDATE cruise_enrollments ce SET
    status = $1,
    updated_at = CURRENT_TIMESTAMP
FROM cruises c
WHERE ce.id = $2 AND ce.cruise_id = c.id AND c.org_id = $3
`

type UpdateCruiseEnrollmentStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
	OrgID  int64  `json:"org_id"`
}

func (q *Queries) UpdateCruiseEnrollmentStatus(ctx context.Context, arg UpdateCruiseEnrollmentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCruiseEnrollmentStatus, arg.Status, arg.ID, arg.OrgID)
	return err
}
