// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cruises.sql

package sqlcdb

import (
	"context"

	types "github.com/marcinskalski/sailor-buddy/backend/internal/types"
)

const clearCruiseEnrollToken = `-- name: ClearCruiseEnrollToken :exec
UPDATE cruises SET enroll_token = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

// ClearCruiseEnrollToken
//
//	UPDATE cruises SET enroll_token = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = $1
func (q *Queries) ClearCruiseEnrollToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearCruiseEnrollToken, id)
	return err
}

const countCruises = `-- name: CountCruises :one
SELECT COUNT(*)::BIGINT FROM cruises
`

// CountCruises
//
//	SELECT COUNT(*)::BIGINT FROM cruises
func (q *Queries) CountCruises(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCruises)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCruise = `-- name: CreateCruise :one
INSERT INTO cruises (
    created_by, name, embark_date, disembark_date, countries, start_port, end_port,
    description, image_logo_url, image_photo_url, image_route_url,
    max_crew, cost_per_person
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) RETURNING id, created_by, name, embark_date, disembark_date, countries, start_port, end_port, description, image_logo_url, image_photo_url, image_route_url, max_crew, cost_per_person, enroll_token, created_at, updated_at
`

type CreateCruiseParams struct {
	CreatedBy     types.NullInt64   `json:"created_by"`
	Name          string            `json:"name"`
	EmbarkDate    types.NullString  `json:"embark_date"`
	DisembarkDate types.NullString  `json:"disembark_date"`
	Countries     types.NullString  `json:"countries"`
	StartPort     types.NullString  `json:"start_port"`
	EndPort       types.NullString  `json:"end_port"`
	Description   types.NullString  `json:"description"`
	ImageLogoUrl  types.NullString  `json:"image_logo_url"`
	ImagePhotoUrl types.NullString  `json:"image_photo_url"`
	ImageRouteUrl types.NullString  `json:"image_route_url"`
	MaxCrew       types.NullInt64   `json:"max_crew"`
	CostPerPerson types.NullFloat64 `json:"cost_per_person"`
}

// CreateCruise
//
//	INSERT INTO cruises (
//	    created_by, name, embark_date, disembark_date, countries, start_port, end_port,
//	    description, image_logo_url, image_photo_url, image_route_url,
//	    max_crew, cost_per_person
//	) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) RETURNING id, created_by, name, embark_date, disembark_date, countries, start_port, end_port, description, image_logo_url, image_photo_url, image_route_url, max_crew, cost_per_person, enroll_token, created_at, updated_at
func (q *Queries) CreateCruise(ctx context.Context, arg CreateCruiseParams) (Cruise, error) {
	row := q.db.QueryRowContext(ctx, createCruise,
		arg.CreatedBy,
		arg.Name,
		arg.EmbarkDate,
		arg.DisembarkDate,
		arg.Countries,
		arg.StartPort,
		arg.EndPort,
		arg.Description,
		arg.ImageLogoUrl,
		arg.ImagePhotoUrl,
		arg.ImageRouteUrl,
		arg.MaxCrew,
		arg.CostPerPerson,
	)
	var i Cruise
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Name,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.Description,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.MaxCrew,
		&i.CostPerPerson,
		&i.EnrollToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCruise = `-- name: DeleteCruise :exec
DELETE FROM cruises WHERE id = $1
`

// DeleteCruise
//
//	DELETE FROM cruises WHERE id = $1
func (q *Queries) DeleteCruise(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCruise, id)
	return err
}

const getCruise = `-- name: GetCruise :one
SELECT id, created_by, name, embark_date, disembark_date, countries, start_port, end_port, description, image_logo_url, image_photo_url, image_route_url, max_crew, cost_per_person, enroll_token, created_at, updated_at FROM cruises WHERE id = $1
`

// GetCruise
//
//	SELECT id, created_by, name, embark_date, disembark_date, countries, start_port, end_port, description, image_logo_url, image_photo_url, image_route_url, max_crew, cost_per_person, enroll_token, created_at, updated_at FROM cruises WHERE id = $1
func (q *Queries) GetCruise(ctx context.Context, id int64) (Cruise, error) {
	row := q.db.QueryRowContext(ctx, getCruise, id)
	var i Cruise
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Name,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.Description,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.MaxCrew,
		&i.CostPerPerson,
		&i.EnrollToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCruiseByEnrollToken = `-- name: GetCruiseByEnrollToken :one
SELECT id, name, embark_date, disembark_date, countries, start_port, end_port,
       description, image_photo_url, max_crew, cost_per_person
FROM cruises WHERE enroll_token = $1
`

type GetCruiseByEnrollTokenRow struct {
	ID            int64             `json:"id"`
	Name          string            `json:"name"`
	EmbarkDate    types.NullString  `json:"embark_date"`
	DisembarkDate types.NullString  `json:"disembark_date"`
	Countries     types.NullString  `json:"countries"`
	StartPort     types.NullString  `json:"start_port"`
	EndPort       types.NullString  `json:"end_port"`
	Description   types.NullString  `json:"description"`
	ImagePhotoUrl types.NullString  `json:"image_photo_url"`
	MaxCrew       types.NullInt64   `json:"max_crew"`
	CostPerPerson types.NullFloat64 `json:"cost_per_person"`
}

// GetCruiseByEnrollToken
//
//	SELECT id, name, embark_date, disembark_date, countries, start_port, end_port,
//	       description, image_photo_url, max_crew, cost_per_person
//	FROM cruises WHERE enroll_token = $1
func (q *Queries) GetCruiseByEnrollToken(ctx context.Context, enrollToken types.NullString) (GetCruiseByEnrollTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getCruiseByEnrollToken, enrollToken)
	var i GetCruiseByEnrollTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.Description,
		&i.ImagePhotoUrl,
		&i.MaxCrew,
		&i.CostPerPerson,
	)
	return i, err
}

const listCruiseTrips = `-- name: ListCruiseTrips :many
SELECT id, created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, cost_total, cost_per_person, max_crew, image_logo_url, image_photo_url, image_route_url, description, status, enroll_token, created_at, updated_at FROM trips WHERE cruise_id = $1 ORDER BY embark_date ASC, id ASC
`

// ListCruiseTrips
//
//	SELECT id, created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, cost_total, cost_per_person, max_crew, image_logo_url, image_photo_url, image_route_url, description, status, enroll_token, created_at, updated_at FROM trips WHERE cruise_id = $1 ORDER BY embark_date ASC, id ASC
func (q *Queries) ListCruiseTrips(ctx context.Context, cruiseID types.NullInt64) ([]Trip, error) {
	rows, err := q.db.QueryContext(ctx, listCruiseTrips, cruiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CruiseID,
			&i.Name,
			&i.EmbarkDate,
			&i.DisembarkDate,
			&i.Countries,
			&i.StartPort,
			&i.EndPort,
			&i.CaptainName,
			&i.YachtID,
			&i.CostTotal,
			&i.CostPerPerson,
			&i.MaxCrew,
			&i.ImageLogoUrl,
			&i.ImagePhotoUrl,
			&i.ImageRouteUrl,
			&i.Description,
			&i.Status,
			&i.EnrollToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCruiseVoyages = `-- name: ListCruiseVoyages :many
SELECT id, created_by, cruise_id, name, year, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at FROM voyages WHERE cruise_id = $1 ORDER BY year DESC, embark_date DESC, id DESC
`

// ListCruiseVoyages
//
//	SELECT id, created_by, cruise_id, name, year, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at FROM voyages WHERE cruise_id = $1 ORDER BY year DESC, embark_date DESC, id DESC
func (q *Queries) ListCruiseVoyages(ctx context.Context, cruiseID types.NullInt64) ([]Voyage, error) {
	rows, err := q.db.QueryContext(ctx, listCruiseVoyages, cruiseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Voyage
	for rows.Next() {
		var i Voyage
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CruiseID,
			&i.Name,
			&i.Year,
			&i.EmbarkDate,
			&i.DisembarkDate,
			&i.Countries,
			&i.StartPort,
			&i.EndPort,
			&i.CaptainName,
			&i.YachtID,
			&i.HoursTotal,
			&i.HoursSail,
			&i.HoursEngine,
			&i.HoursOver6bf,
			&i.Miles,
			&i.Days,
			&i.TidalWaters,
			&i.CostTotal,
			&i.CostPerPerson,
			&i.ImageLogoUrl,
			&i.ImagePhotoUrl,
			&i.ImageRouteUrl,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCruises = `-- name: ListCruises :many
SELECT id, created_by, name, embark_date, disembark_date, countries, start_port, end_port, description, image_logo_url, image_photo_url, image_route_url, max_crew, cost_per_person, enroll_token, created_at, updated_at FROM cruises ORDER BY embark_date DESC NULLS LAST, id DESC LIMIT $1 OFFSET $2
`

type ListCruisesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// ListCruises
//
//	SELECT id, created_by, name, embark_date, disembark_date, countries, start_port, end_port, description, image_logo_url, image_photo_url, image_route_url, max_crew, cost_per_person, enroll_token, created_at, updated_at FROM cruises ORDER BY embark_date DESC NULLS LAST, id DESC LIMIT $1 OFFSET $2
func (q *Queries) ListCruises(ctx context.Context, arg ListCruisesParams) ([]Cruise, error) {
	rows, err := q.db.QueryContext(ctx, listCruises, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cruise
	for rows.Next() {
		var i Cruise
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.Name,
			&i.EmbarkDate,
			&i.DisembarkDate,
			&i.Countries,
			&i.StartPort,
			&i.EndPort,
			&i.Description,
			&i.ImageLogoUrl,
			&i.ImagePhotoUrl,
			&i.ImageRouteUrl,
			&i.MaxCrew,
			&i.CostPerPerson,
			&i.EnrollToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCruiseEnrollToken = `-- name: SetCruiseEnrollToken :exec
UPDATE cruises SET enroll_token = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2
`

type SetCruiseEnrollTokenParams struct {
	EnrollToken types.NullString `json:"enroll_token"`
	ID          int64            `json:"id"`
}

// SetCruiseEnrollToken
//
//	UPDATE cruises SET enroll_token = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2
func (q *Queries) SetCruiseEnrollToken(ctx context.Context, arg SetCruiseEnrollTokenParams) error {
	_, err := q.db.ExecContext(ctx, setCruiseEnrollToken, arg.EnrollToken, arg.ID)
	return err
}

const updateCruise = `-- name: UpdateCruise :exec
UPDATE cruises SET
    name = $1, embark_date = $2, disembark_date = $3, countries = $4,
    start_port = $5, end_port = $6, description = $7,
    image_logo_url = $8, image_photo_url = $9, image_route_url = $10,
    max_crew = $11, cost_per_person = $12,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $13
`

type UpdateCruiseParams struct {
	Name          string            `json:"name"`
	EmbarkDate    types.NullString  `json:"embark_date"`
	DisembarkDate types.NullString  `json:"disembark_date"`
	Countries     types.NullString  `json:"countries"`
	StartPort     types.NullString  `json:"start_port"`
	EndPort       types.NullString  `json:"end_port"`
	Description   types.NullString  `json:"description"`
	ImageLogoUrl  types.NullString  `json:"image_logo_url"`
	ImagePhotoUrl types.NullString  `json:"image_photo_url"`
	ImageRouteUrl types.NullString  `json:"image_route_url"`
	MaxCrew       types.NullInt64   `json:"max_crew"`
	CostPerPerson types.NullFloat64 `json:"cost_per_person"`
	ID            int64             `json:"id"`
}

// UpdateCruise
//
//	UPDATE cruises SET
//	    name = $1, embark_date = $2, disembark_date = $3, countries = $4,
//	    start_port = $5, end_port = $6, description = $7,
//	    image_logo_url = $8, image_photo_url = $9, image_route_url = $10,
//	    max_crew = $11, cost_per_person = $12,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $13
func (q *Queries) UpdateCruise(ctx context.Context, arg UpdateCruiseParams) error {
	_, err := q.db.ExecContext(ctx, updateCruise,
		arg.Name,
		arg.EmbarkDate,
		arg.DisembarkDate,
		arg.Countries,
		arg.StartPort,
		arg.EndPort,
		arg.Description,
		arg.ImageLogoUrl,
		arg.ImagePhotoUrl,
		arg.ImageRouteUrl,
		arg.MaxCrew,
		arg.CostPerPerson,
		arg.ID,
	)
	return err
}
