// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const addOrgMember = `-- name: AddOrgMember :one
INSERT INTO org_members (org_id, user_id, role)
VALUES ($1, $2, $3) RETURNING id, org_id, user_id, role, joined_at
`

type AddOrgMemberParams struct {
	OrgID  int64  `json:"org_id"`
	UserID int64  `json:"user_id"`
	Role   string `json:"role"`
}

func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRowContext(ctx, addOrgMember, arg.OrgID, arg.UserID, arg.Role)
	var i OrgMember
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const countOrgAdmins = `-- name: CountOrgAdmins :one
SELECT COUNT(*)::BIGINT FROM org_members WHERE org_id = $1 AND role = 'admin'
`

func (q *Queries) CountOrgAdmins(ctx context.Context, orgID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrgAdmins, orgID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOrgInvite = `-- name: CreateOrgInvite :one
INSERT INTO org_invites (org_id, token, role, created_by, expires_at, max_uses)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, org_id, token, role, created_by, expires_at, max_uses, use_count, created_at
`

type CreateOrgInviteParams struct {
	OrgID     int64         `json:"org_id"`
	Token     string        `json:"token"`
	Role      string        `json:"role"`
	CreatedBy int64         `json:"created_by"`
	ExpiresAt sql.NullTime  `json:"expires_at"`
	MaxUses   sql.NullInt64 `json:"max_uses"`
}

func (q *Queries) CreateOrgInvite(ctx context.Context, arg CreateOrgInviteParams) (OrgInvite, error) {
	row := q.db.QueryRowContext(ctx, createOrgInvite,
		arg.OrgID,
		arg.Token,
		arg.Role,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.MaxUses,
	)
	var i OrgInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Token,
		&i.Role,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug, description, logo_url, pzz_club_number, city, website)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, name, slug, description, logo_url, pzz_club_number, city, website, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name          string         `json:"name"`
	Slug          string         `json:"slug"`
	Description   sql.NullString `json:"description"`
	LogoUrl       sql.NullString `json:"logo_url"`
	PzzClubNumber sql.NullString `json:"pzz_club_number"`
	City          sql.NullString `json:"city"`
	Website       sql.NullString `json:"website"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganization,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.LogoUrl,
		arg.PzzClubNumber,
		arg.City,
		arg.Website,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.PzzClubNumber,
		&i.City,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrgInvite = `-- name: DeleteOrgInvite :exec
DELETE FROM org_invites WHERE id = $1 AND org_id = $2
`

type DeleteOrgInviteParams struct {
	ID    int64 `json:"id"`
	OrgID int64 `json:"org_id"`
}

func (q *Queries) DeleteOrgInvite(ctx context.Context, arg DeleteOrgInviteParams) error {
	_, err := q.db.ExecContext(ctx, deleteOrgInvite, arg.ID, arg.OrgID)
	return err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrganization, id)
	return err
}

const getOrgInviteByToken = `-- name: GetOrgInviteByToken :one
SELECT oi.id, oi.org_id, oi.token, oi.role, oi.created_by, oi.expires_at, oi.max_uses, oi.use_count, oi.created_at, o.name AS org_name, o.slug AS org_slug
FROM org_invites oi
JOIN organizations o ON o.id = oi.org_id
WHERE oi.token = $1
`

type GetOrgInviteByTokenRow struct {
	ID        int64         `json:"id"`
	OrgID     int64         `json:"org_id"`
	Token     string        `json:"token"`
	Role      string        `json:"role"`
	CreatedBy int64         `json:"created_by"`
	ExpiresAt sql.NullTime  `json:"expires_at"`
	MaxUses   sql.NullInt64 `json:"max_uses"`
	UseCount  int64         `json:"use_count"`
	CreatedAt sql.NullTime  `json:"created_at"`
	OrgName   string        `json:"org_name"`
	OrgSlug   string        `json:"org_slug"`
}

func (q *Queries) GetOrgInviteByToken(ctx context.Context, token string) (GetOrgInviteByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getOrgInviteByToken, token)
	var i GetOrgInviteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Token,
		&i.Role,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UseCount,
		&i.CreatedAt,
		&i.OrgName,
		&i.OrgSlug,
	)
	return i, err
}

const getOrgMembership = `-- name: GetOrgMembership :one
SELECT om.id, om.org_id, om.user_id, om.role, om.joined_at, o.slug
FROM org_members om
JOIN organizations o ON o.id = om.org_id
WHERE om.org_id = $1 AND om.user_id = $2
`

type GetOrgMembershipParams struct {
	OrgID  int64 `json:"org_id"`
	UserID int64 `json:"user_id"`
}

type GetOrgMembershipRow struct {
	ID       int64        `json:"id"`
	OrgID    int64        `json:"org_id"`
	UserID   int64        `json:"user_id"`
	Role     string       `json:"role"`
	JoinedAt sql.NullTime `json:"joined_at"`
	Slug     string       `json:"slug"`
}

func (q *Queries) GetOrgMembership(ctx context.Context, arg GetOrgMembershipParams) (GetOrgMembershipRow, error) {
	row := q.db.QueryRowContext(ctx, getOrgMembership, arg.OrgID, arg.UserID)
	var i GetOrgMembershipRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.Slug,
	)
	return i, err
}

const getOrgMembershipBySlug = `-- name: GetOrgMembershipBySlug :one
SELECT om.id, om.org_id, om.user_id, om.role, om.joined_at
FROM org_members om
JOIN organizations o ON o.id = om.org_id
WHERE o.slug = $1 AND om.user_id = $2
`

type GetOrgMembershipBySlugParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) GetOrgMembershipBySlug(ctx context.Context, arg GetOrgMembershipBySlugParams) (OrgMember, error) {
	row := q.db.QueryRowContext(ctx, getOrgMembershipBySlug, arg.Slug, arg.UserID)
	var i OrgMember
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, description, logo_url, pzz_club_number, city, website, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.PzzClubNumber,
		&i.City,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, description, logo_url, pzz_club_number, city, website, created_at, updated_at FROM organizations WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.PzzClubNumber,
		&i.City,
		&i.Website,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementInviteUseCount = `-- name: IncrementInviteUseCount :exec
UPDATE org_invites SET use_count = use_count + 1 WHERE id = $1
`

func (q *Queries) IncrementInviteUseCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementInviteUseCount, id)
	return err
}

const listOrgInvites = `-- name: ListOrgInvites :many
SELECT oi.id, oi.org_id, oi.token, oi.role, oi.created_by, oi.expires_at, oi.max_uses, oi.use_count, oi.created_at, u.name AS creator_name
FROM org_invites oi
JOIN users u ON u.id = oi.created_by
WHERE oi.org_id = $1
ORDER BY oi.created_at DESC
`

type ListOrgInvitesRow struct {
	ID          int64         `json:"id"`
	OrgID       int64         `json:"org_id"`
	Token       string        `json:"token"`
	Role        string        `json:"role"`
	CreatedBy   int64         `json:"created_by"`
	ExpiresAt   sql.NullTime  `json:"expires_at"`
	MaxUses     sql.NullInt64 `json:"max_uses"`
	UseCount    int64         `json:"use_count"`
	CreatedAt   sql.NullTime  `json:"created_at"`
	CreatorName string        `json:"creator_name"`
}

func (q *Queries) ListOrgInvites(ctx context.Context, orgID int64) ([]ListOrgInvitesRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrgInvites, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgInvitesRow
	for rows.Next() {
		var i ListOrgInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Token,
			&i.Role,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.UseCount,
			&i.CreatedAt,
			&i.CreatorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT om.id, om.org_id, om.user_id, om.role, om.joined_at,
       u.name AS user_name, u.email AS user_email, u.avatar_url AS user_avatar_url
FROM org_members om
JOIN users u ON u.id = om.user_id
WHERE om.org_id = $1
ORDER BY om.role, u.name
`

type ListOrgMembersRow struct {
	ID            int64          `json:"id"`
	OrgID         int64          `json:"org_id"`
	UserID        int64          `json:"user_id"`
	Role          string         `json:"role"`
	JoinedAt      sql.NullTime   `json:"joined_at"`
	UserName      string         `json:"user_name"`
	UserEmail     string         `json:"user_email"`
	UserAvatarUrl sql.NullString `json:"user_avatar_url"`
}

func (q *Queries) ListOrgMembers(ctx context.Context, orgID int64) ([]ListOrgMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgMembersRow
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrganizations = `-- name: ListUserOrganizations :many
SELECT o.id, o.name, o.slug, o.description, o.logo_url, o.pzz_club_number, o.city, o.website, o.created_at, o.updated_at, om.role
FROM organizations o
JOIN org_members om ON om.org_id = o.id
WHERE om.user_id = $1
ORDER BY o.name
`

type ListUserOrganizationsRow struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Slug          string         `json:"slug"`
	Description   sql.NullString `json:"description"`
	LogoUrl       sql.NullString `json:"logo_url"`
	PzzClubNumber sql.NullString `json:"pzz_club_number"`
	City          sql.NullString `json:"city"`
	Website       sql.NullString `json:"website"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	Role          string         `json:"role"`
}

func (q *Queries) ListUserOrganizations(ctx context.Context, userID int64) ([]ListUserOrganizationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserOrganizationsRow
	for rows.Next() {
		var i ListUserOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.LogoUrl,
			&i.PzzClubNumber,
			&i.City,
			&i.Website,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeOrgMember = `-- name: RemoveOrgMember :exec
DELETE FROM org_members WHERE id = $1 AND org_id = $2
`

type RemoveOrgMemberParams struct {
	ID    int64 `json:"id"`
	OrgID int64 `json:"org_id"`
}

func (q *Queries) RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeOrgMember, arg.ID, arg.OrgID)
	return err
}

const updateOrgMemberRole = `-- name: UpdateOrgMemberRole :exec
UPDATE org_members SET role = $1 WHERE id = $2 AND org_id = $3
`

type UpdateOrgMemberRoleParams struct {
	Role  string `json:"role"`
	ID    int64  `json:"id"`
	OrgID int64  `json:"org_id"`
}

func (q *Queries) UpdateOrgMemberRole(ctx context.Context, arg UpdateOrgMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateOrgMemberRole, arg.Role, arg.ID, arg.OrgID)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations SET
    name = $1, description = $2, logo_url = $3,
    pzz_club_number = $4, city = $5, website = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $7
`

type UpdateOrganizationParams struct {
	Name          string         `json:"name"`
	Description   sql.NullString `json:"description"`
	LogoUrl       sql.NullString `json:"logo_url"`
	PzzClubNumber sql.NullString `json:"pzz_club_number"`
	City          sql.NullString `json:"city"`
	Website       sql.NullString `json:"website"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganization,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
		arg.PzzClubNumber,
		arg.City,
		arg.Website,
		arg.ID,
	)
	return err
}
