// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"

	types "github.com/marcinskalski/sailor-buddy/backend/internal/types"
)

type Querier interface {
	//AssignCruiseEnrollmentToTrip
	//
	//  UPDATE cruise_enrollments ce SET
	//      trip_id = $1,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE ce.id = $2
	//    AND ($1::BIGINT IS NULL OR EXISTS (
	//        SELECT 1 FROM trips t WHERE t.id = $1 AND t.cruise_id = ce.cruise_id
	//    ))
	AssignCruiseEnrollmentToTrip(ctx context.Context, arg AssignCruiseEnrollmentToTripParams) error
	//CancelTrip
	//
	//  UPDATE trips SET status = 'cancelled', enroll_token = NULL, updated_at = CURRENT_TIMESTAMP
	//  WHERE id = $1 AND status = 'planned' RETURNING id, created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, cost_total, cost_per_person, max_crew, image_logo_url, image_photo_url, image_route_url, description, status, enroll_token, created_at, updated_at
	CancelTrip(ctx context.Context, id int64) (Trip, error)
	//ClearCruiseEnrollToken
	//
	//  UPDATE cruises SET enroll_token = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = $1
	ClearCruiseEnrollToken(ctx context.Context, id int64) error
	//ClearTripEnrollToken
	//
	//  UPDATE trips SET enroll_token = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = $1
	ClearTripEnrollToken(ctx context.Context, id int64) error
	//CountAdmins
	//
	//  SELECT COUNT(*)::BIGINT FROM users WHERE role = 'admin'
	CountAdmins(ctx context.Context) (int64, error)
	//CountCrewMembers
	//
	//  SELECT COUNT(*)::BIGINT FROM crew_members
	CountCrewMembers(ctx context.Context) (int64, error)
	//CountCruiseEnrollments
	//
	//  SELECT
	//      COUNT(*) FILTER (WHERE status = 'accepted')::BIGINT AS accepted,
	//      COUNT(*)::BIGINT AS total
	//  FROM cruise_enrollments
	//  WHERE cruise_id = $1
	CountCruiseEnrollments(ctx context.Context, cruiseID int64) (CountCruiseEnrollmentsRow, error)
	//CountCruises
	//
	//  SELECT COUNT(*)::BIGINT FROM cruises
	CountCruises(ctx context.Context) (int64, error)
	//CountTrainings
	//
	//  SELECT COUNT(*)::BIGINT FROM trainings WHERE user_id = $1
	CountTrainings(ctx context.Context, userID int64) (int64, error)
	//CountTripEnrollments
	//
	//  SELECT
	//      COUNT(*) FILTER (WHERE status = 'accepted')::BIGINT AS accepted,
	//      COUNT(*)::BIGINT AS total
	//  FROM trip_enrollments
	//  WHERE trip_id = $1
	CountTripEnrollments(ctx context.Context, tripID int64) (CountTripEnrollmentsRow, error)
	//CountTrips
	//
	//  SELECT COUNT(*)::BIGINT FROM trips
	CountTrips(ctx context.Context) (int64, error)
	//CountUsers
	//
	//  SELECT COUNT(*)::BIGINT FROM users
	CountUsers(ctx context.Context) (int64, error)
	//CountVoyages
	//
	//  SELECT COUNT(*)::BIGINT FROM voyages
	CountVoyages(ctx context.Context) (int64, error)
	//CountYachts
	//
	//  SELECT COUNT(*)::BIGINT FROM yachts
	CountYachts(ctx context.Context) (int64, error)
	//CreateCrewMember
	//
	//  INSERT INTO crew_members (
	//      created_by, user_id, full_name, email, patent_number,
	//      phone, pzz_license_type, pzz_license_number,
	//      emergency_contact_name, emergency_contact_phone
	//  ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, created_by, user_id, full_name, email, patent_number, phone, pzz_license_type, pzz_license_number, emergency_contact_name, emergency_contact_phone, created_at, updated_at
	CreateCrewMember(ctx context.Context, arg CreateCrewMemberParams) (CrewMember, error)
	//CreateCruise
	//
	//  INSERT INTO cruises (
	//      created_by, name, embark_date, disembark_date, countries, start_port, end_port,
	//      description, image_logo_url, image_photo_url, image_route_url,
	//      max_crew, cost_per_person
	//  ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) RETURNING id, created_by, name, embark_date, disembark_date, countries, start_port, end_port, description, image_logo_url, image_photo_url, image_route_url, max_crew, cost_per_person, enroll_token, created_at, updated_at
	CreateCruise(ctx context.Context, arg CreateCruiseParams) (Cruise, error)
	//CreateCruiseEnrollment
	//
	//  INSERT INTO cruise_enrollments (cruise_id, user_id, note)
	//  VALUES ($1, $2, $3) RETURNING id, cruise_id, user_id, trip_id, note, status, created_at, updated_at
	CreateCruiseEnrollment(ctx context.Context, arg CreateCruiseEnrollmentParams) (CruiseEnrollment, error)
	//CreateTraining
	//
	//  INSERT INTO trainings (user_id, date, name, organizer, cost, url) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, date, name, organizer, cost, url, created_at, updated_at
	CreateTraining(ctx context.Context, arg CreateTrainingParams) (Training, error)
	//CreateTrip
	//
	//  INSERT INTO trips (
	//      created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port,
	//      captain_name, yacht_id, cost_total, cost_per_person, max_crew,
	//      image_logo_url, image_photo_url, image_route_url, description, status
	//  ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) RETURNING id, created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, cost_total, cost_per_person, max_crew, image_logo_url, image_photo_url, image_route_url, description, status, enroll_token, created_at, updated_at
	CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error)
	//CreateTripCrewAssignment
	//
	//  INSERT INTO crew_assignments (trip_id, crew_member_id, role, patent_number)
	//  VALUES ($1, $2, $3, $4) RETURNING id, trip_id, voyage_id, crew_member_id, role, patent_number, created_at
	CreateTripCrewAssignment(ctx context.Context, arg CreateTripCrewAssignmentParams) (CrewAssignment, error)
	//CreateTripEnrollment
	//
	//  INSERT INTO trip_enrollments (trip_id, user_id, note)
	//  VALUES ($1, $2, $3) RETURNING id, trip_id, user_id, note, status, created_at, updated_at
	CreateTripEnrollment(ctx context.Context, arg CreateTripEnrollmentParams) (TripEnrollment, error)
	//CreateUser
	//
	//  INSERT INTO users (email, name, password_hash, firebase_uid) VALUES ($1, $2, '', $3) RETURNING id, email, name, password_hash, avatar_url, firebase_uid, role, patent_type, patent_number, created_at, updated_at
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	//CreateVoyage
	//
	//  INSERT INTO voyages (
	//      created_by, cruise_id, name, year, embark_date, disembark_date, countries, start_port, end_port,
	//      captain_name, yacht_id,
	//      hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, tidal_waters,
	//      cost_total, cost_per_person,
	//      image_logo_url, image_photo_url, image_route_url, description
	//  ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24) RETURNING id, created_by, cruise_id, name, year, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at
	CreateVoyage(ctx context.Context, arg CreateVoyageParams) (Voyage, error)
	//CreateVoyageCrewAssignment
	//
	//  INSERT INTO crew_assignments (voyage_id, crew_member_id, role, patent_number)
	//  VALUES ($1, $2, $3, $4) RETURNING id, trip_id, voyage_id, crew_member_id, role, patent_number, created_at
	CreateVoyageCrewAssignment(ctx context.Context, arg CreateVoyageCrewAssignmentParams) (CrewAssignment, error)
	//CreateVoyageOpinion
	//
	//  INSERT INTO voyage_opinions (voyage_id, crew_member_id, file_path, file_format) VALUES ($1, $2, $3, $4) RETURNING id, voyage_id, crew_member_id, file_path, file_format, created_at
	CreateVoyageOpinion(ctx context.Context, arg CreateVoyageOpinionParams) (VoyageOpinion, error)
	//CreateVoyagePort
	//
	//  INSERT INTO voyage_ports (voyage_id, name, latitude, longitude, position)
	//  VALUES ($1, $2, $3, $4, $5) RETURNING id, voyage_id, name, latitude, longitude, position, created_at
	CreateVoyagePort(ctx context.Context, arg CreateVoyagePortParams) (VoyagePort, error)
	//CreateYacht
	//
	//  INSERT INTO yachts (created_by, name, registration_no, yacht_type)
	//  VALUES ($1, $2, $3, $4) RETURNING id, created_by, name, registration_no, yacht_type, created_at, updated_at
	CreateYacht(ctx context.Context, arg CreateYachtParams) (Yacht, error)
	//DeleteCrewMember
	//
	//  DELETE FROM crew_members WHERE id = $1
	DeleteCrewMember(ctx context.Context, id int64) error
	//DeleteCruise
	//
	//  DELETE FROM cruises WHERE id = $1
	DeleteCruise(ctx context.Context, id int64) error
	//DeleteCruiseEnrollment
	//
	//  DELETE FROM cruise_enrollments WHERE id = $1
	DeleteCruiseEnrollment(ctx context.Context, id int64) error
	//DeleteTraining
	//
	//  DELETE FROM trainings WHERE id = $1 AND user_id = $2
	DeleteTraining(ctx context.Context, arg DeleteTrainingParams) error
	//DeleteTrip
	//
	//  DELETE FROM trips WHERE id = $1
	DeleteTrip(ctx context.Context, id int64) error
	//DeleteTripCrewAssignment
	//
	//  DELETE FROM crew_assignments WHERE id = $1 AND trip_id = $2
	DeleteTripCrewAssignment(ctx context.Context, arg DeleteTripCrewAssignmentParams) error
	//DeleteTripEnrollment
	//
	//  DELETE FROM trip_enrollments WHERE id = $1
	DeleteTripEnrollment(ctx context.Context, id int64) error
	//DeleteTripEnrollmentsForTrip
	//
	//  DELETE FROM trip_enrollments WHERE trip_id = $1
	DeleteTripEnrollmentsForTrip(ctx context.Context, tripID int64) error
	//DeleteVoyage
	//
	//  DELETE FROM voyages WHERE id = $1
	DeleteVoyage(ctx context.Context, id int64) error
	//DeleteVoyageCrewAssignment
	//
	//  DELETE FROM crew_assignments WHERE id = $1 AND voyage_id = $2
	DeleteVoyageCrewAssignment(ctx context.Context, arg DeleteVoyageCrewAssignmentParams) error
	//DeleteVoyageOpinion
	//
	//  DELETE FROM voyage_opinions WHERE id = $1
	DeleteVoyageOpinion(ctx context.Context, id int64) error
	//DeleteVoyagePort
	//
	//  DELETE FROM voyage_ports WHERE id = $1 AND voyage_id = $2
	DeleteVoyagePort(ctx context.Context, arg DeleteVoyagePortParams) error
	//DeleteYacht
	//
	//  DELETE FROM yachts WHERE id = $1
	DeleteYacht(ctx context.Context, id int64) error
	//GetCrewMember
	//
	//  SELECT id, created_by, user_id, full_name, email, patent_number, phone, pzz_license_type, pzz_license_number, emergency_contact_name, emergency_contact_phone, created_at, updated_at FROM crew_members WHERE id = $1
	GetCrewMember(ctx context.Context, id int64) (CrewMember, error)
	//GetCrewMemberByName
	//
	//  SELECT id, created_by, user_id, full_name, email, patent_number, phone, pzz_license_type, pzz_license_number, emergency_contact_name, emergency_contact_phone, created_at, updated_at FROM crew_members WHERE full_name = $1
	GetCrewMemberByName(ctx context.Context, fullName string) (CrewMember, error)
	//GetCrewMemberStats
	//
	//  SELECT
	//      COUNT(*)::BIGINT AS voyage_count,
	//      COALESCE(SUM(v.hours_total), 0)::DOUBLE PRECISION AS total_hours,
	//      COALESCE(SUM(v.miles), 0)::DOUBLE PRECISION AS total_miles,
	//      COALESCE(SUM(v.days), 0)::BIGINT AS total_days
	//  FROM crew_assignments ca
	//  JOIN voyages v ON v.id = ca.voyage_id
	//  WHERE ca.crew_member_id = $1
	GetCrewMemberStats(ctx context.Context, crewMemberID int64) (GetCrewMemberStatsRow, error)
	//GetCrewMemberTrips
	//
	//  SELECT t.id, t.created_by, t.cruise_id, t.name, t.embark_date, t.disembark_date, t.countries, t.start_port, t.end_port, t.captain_name, t.yacht_id, t.cost_total, t.cost_per_person, t.max_crew, t.image_logo_url, t.image_photo_url, t.image_route_url, t.description, t.status, t.enroll_token, t.created_at, t.updated_at, ca.role
	//  FROM crew_assignments ca
	//  JOIN trips t ON t.id = ca.trip_id
	//  WHERE ca.crew_member_id = $1
	//  ORDER BY t.embark_date ASC
	GetCrewMemberTrips(ctx context.Context, crewMemberID int64) ([]GetCrewMemberTripsRow, error)
	//GetCrewMemberVoyages
	//
	//  SELECT v.id, v.created_by, v.cruise_id, v.name, v.year, v.embark_date, v.disembark_date, v.countries, v.start_port, v.end_port, v.captain_name, v.yacht_id, v.hours_total, v.hours_sail, v.hours_engine, v.hours_over_6bf, v.miles, v.days, v.tidal_waters, v.cost_total, v.cost_per_person, v.image_logo_url, v.image_photo_url, v.image_route_url, v.description, v.created_at, v.updated_at, ca.role
	//  FROM crew_assignments ca
	//  JOIN voyages v ON v.id = ca.voyage_id
	//  WHERE ca.crew_member_id = $1
	//  ORDER BY v.year DESC, v.embark_date DESC
	GetCrewMemberVoyages(ctx context.Context, crewMemberID int64) ([]GetCrewMemberVoyagesRow, error)
	//GetCruise
	//
	//  SELECT id, created_by, name, embark_date, disembark_date, countries, start_port, end_port, description, image_logo_url, image_photo_url, image_route_url, max_crew, cost_per_person, enroll_token, created_at, updated_at FROM cruises WHERE id = $1
	GetCruise(ctx context.Context, id int64) (Cruise, error)
	//GetCruiseByEnrollToken
	//
	//  SELECT id, name, embark_date, disembark_date, countries, start_port, end_port,
	//         description, image_photo_url, max_crew, cost_per_person
	//  FROM cruises WHERE enroll_token = $1
	GetCruiseByEnrollToken(ctx context.Context, enrollToken types.NullString) (GetCruiseByEnrollTokenRow, error)
	//GetDashboardStats
	//
	//  SELECT
	//      COUNT(*)::BIGINT AS voyage_count,
	//      COALESCE(SUM(hours_total), 0)::DOUBLE PRECISION AS total_hours,
	//      COALESCE(SUM(miles), 0)::DOUBLE PRECISION AS total_miles,
	//      COALESCE(SUM(days), 0)::BIGINT AS total_days,
	//      COALESCE(SUM(hours_sail), 0)::DOUBLE PRECISION AS total_hours_sail,
	//      COALESCE(SUM(hours_engine), 0)::DOUBLE PRECISION AS total_hours_engine
	//  FROM voyages
	GetDashboardStats(ctx context.Context) (GetDashboardStatsRow, error)
	//GetTraining
	//
	//  SELECT id, user_id, date, name, organizer, cost, url, created_at, updated_at FROM trainings WHERE id = $1 AND user_id = $2
	GetTraining(ctx context.Context, arg GetTrainingParams) (Training, error)
	//GetTrip
	//
	//  SELECT id, created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, cost_total, cost_per_person, max_crew, image_logo_url, image_photo_url, image_route_url, description, status, enroll_token, created_at, updated_at FROM trips WHERE id = $1
	GetTrip(ctx context.Context, id int64) (Trip, error)
	//GetTripByEnrollToken
	//
	//  SELECT id, name, embark_date, disembark_date, countries, start_port, end_port,
	//         description, max_crew, captain_name, image_photo_url
	//  FROM trips WHERE enroll_token = $1
	GetTripByEnrollToken(ctx context.Context, enrollToken types.NullString) (GetTripByEnrollTokenRow, error)
	//GetTripStatus
	//
	//  SELECT status FROM trips WHERE id = $1
	GetTripStatus(ctx context.Context, id int64) (TripStatus, error)
	//GetUserByEmail
	//
	//  SELECT id, email, name, password_hash, avatar_url, firebase_uid, role, patent_type, patent_number, created_at, updated_at FROM users WHERE email = $1
	GetUserByEmail(ctx context.Context, email string) (User, error)
	//GetUserByFirebaseUID
	//
	//  SELECT id, email, name, password_hash, avatar_url, firebase_uid, role, patent_type, patent_number, created_at, updated_at FROM users WHERE firebase_uid = $1
	GetUserByFirebaseUID(ctx context.Context, firebaseUid types.NullString) (User, error)
	//GetUserByID
	//
	//  SELECT id, email, name, password_hash, avatar_url, firebase_uid, role, patent_type, patent_number, created_at, updated_at FROM users WHERE id = $1
	GetUserByID(ctx context.Context, id int64) (User, error)
	//GetUserCruiseEnrollment
	//
	//  SELECT id, cruise_id, user_id, trip_id, note, status, created_at, updated_at FROM cruise_enrollments
	//  WHERE cruise_id = $1 AND user_id = $2
	GetUserCruiseEnrollment(ctx context.Context, arg GetUserCruiseEnrollmentParams) (CruiseEnrollment, error)
	//GetUserTripEnrollment
	//
	//  SELECT id, trip_id, user_id, note, status, created_at, updated_at FROM trip_enrollments
	//  WHERE trip_id = $1 AND user_id = $2
	GetUserTripEnrollment(ctx context.Context, arg GetUserTripEnrollmentParams) (TripEnrollment, error)
	//GetVoyage
	//
	//  SELECT id, created_by, cruise_id, name, year, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at FROM voyages WHERE id = $1
	GetVoyage(ctx context.Context, id int64) (Voyage, error)
	//GetVoyageCrewAssignmentByMember
	//
	//  SELECT ca.id, ca.trip_id, ca.voyage_id, ca.crew_member_id, ca.role, ca.patent_number, ca.created_at, cm.full_name, cm.patent_number AS member_patent
	//  FROM crew_assignments ca
	//  JOIN crew_members cm ON cm.id = ca.crew_member_id
	//  WHERE ca.voyage_id = $1 AND ca.crew_member_id = $2
	GetVoyageCrewAssignmentByMember(ctx context.Context, arg GetVoyageCrewAssignmentByMemberParams) (GetVoyageCrewAssignmentByMemberRow, error)
	//GetVoyageOpinion
	//
	//  SELECT id, voyage_id, crew_member_id, file_path, file_format, created_at FROM voyage_opinions WHERE id = $1
	GetVoyageOpinion(ctx context.Context, id int64) (VoyageOpinion, error)
	//GetVoyagesByYear
	//
	//  SELECT
	//      year,
	//      COUNT(*)::BIGINT AS voyage_count,
	//      COALESCE(SUM(hours_total), 0)::DOUBLE PRECISION AS total_hours,
	//      COALESCE(SUM(miles), 0)::DOUBLE PRECISION AS total_miles,
	//      COALESCE(SUM(days), 0)::BIGINT AS total_days
	//  FROM voyages GROUP BY year ORDER BY year
	GetVoyagesByYear(ctx context.Context) ([]GetVoyagesByYearRow, error)
	//GetYacht
	//
	//  SELECT id, created_by, name, registration_no, yacht_type, created_at, updated_at FROM yachts WHERE id = $1
	GetYacht(ctx context.Context, id int64) (Yacht, error)
	//GetYachtByName
	//
	//  SELECT id, created_by, name, registration_no, yacht_type, created_at, updated_at FROM yachts WHERE name = $1
	GetYachtByName(ctx context.Context, name string) (Yacht, error)
	//LinkFirebaseUIDByEmail
	//
	//  UPDATE users SET
	//    firebase_uid = $1,
	//    name = COALESCE(NULLIF($2::TEXT, ''), name),
	//    updated_at = CURRENT_TIMESTAMP
	//  WHERE email = $3
	//    AND (firebase_uid IS NULL OR firebase_uid = $1)
	//  RETURNING id, email, name, password_hash, avatar_url, firebase_uid, role, patent_type, patent_number, created_at, updated_at
	LinkFirebaseUIDByEmail(ctx context.Context, arg LinkFirebaseUIDByEmailParams) (User, error)
	//ListCrewMembers
	//
	//  SELECT id, created_by, user_id, full_name, email, patent_number, phone, pzz_license_type, pzz_license_number, emergency_contact_name, emergency_contact_phone, created_at, updated_at FROM crew_members ORDER BY full_name, id LIMIT $1 OFFSET $2
	ListCrewMembers(ctx context.Context, arg ListCrewMembersParams) ([]CrewMember, error)
	//ListCruiseEnrollments
	//
	//  SELECT ce.id, ce.cruise_id, ce.user_id, ce.trip_id, ce.note, ce.status, ce.created_at, ce.updated_at,
	//         u.name AS user_name, u.email AS user_email,
	//         t.name AS trip_name
	//  FROM cruise_enrollments ce
	//  JOIN users u ON u.id = ce.user_id
	//  LEFT JOIN trips t ON t.id = ce.trip_id
	//  WHERE ce.cruise_id = $1
	//  ORDER BY ce.created_at
	ListCruiseEnrollments(ctx context.Context, cruiseID int64) ([]ListCruiseEnrollmentsRow, error)
	//ListCruiseTrips
	//
	//  SELECT id, created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, cost_total, cost_per_person, max_crew, image_logo_url, image_photo_url, image_route_url, description, status, enroll_token, created_at, updated_at FROM trips WHERE cruise_id = $1 ORDER BY embark_date ASC, id ASC
	ListCruiseTrips(ctx context.Context, cruiseID types.NullInt64) ([]Trip, error)
	//ListCruiseVoyages
	//
	//  SELECT id, created_by, cruise_id, name, year, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at FROM voyages WHERE cruise_id = $1 ORDER BY year DESC, embark_date DESC, id DESC
	ListCruiseVoyages(ctx context.Context, cruiseID types.NullInt64) ([]Voyage, error)
	//ListCruises
	//
	//  SELECT id, created_by, name, embark_date, disembark_date, countries, start_port, end_port, description, image_logo_url, image_photo_url, image_route_url, max_crew, cost_per_person, enroll_token, created_at, updated_at FROM cruises ORDER BY embark_date DESC NULLS LAST, id DESC LIMIT $1 OFFSET $2
	ListCruises(ctx context.Context, arg ListCruisesParams) ([]Cruise, error)
	//ListTrainings
	//
	//  SELECT id, user_id, date, name, organizer, cost, url, created_at, updated_at FROM trainings WHERE user_id = $1 ORDER BY date DESC, id DESC LIMIT $2 OFFSET $3
	ListTrainings(ctx context.Context, arg ListTrainingsParams) ([]Training, error)
	//ListTripCrewAssignments
	//
	//  SELECT ca.id, ca.trip_id, ca.voyage_id, ca.crew_member_id, ca.role, ca.patent_number, ca.created_at,
	//         cm.full_name, cm.email
	//  FROM crew_assignments ca
	//  JOIN crew_members cm ON cm.id = ca.crew_member_id
	//  WHERE ca.trip_id = $1
	//  ORDER BY cm.full_name
	ListTripCrewAssignments(ctx context.Context, tripID types.NullInt64) ([]ListTripCrewAssignmentsRow, error)
	//ListTripEnrollments
	//
	//  SELECT te.id, te.trip_id, te.user_id, te.note, te.status, te.created_at, te.updated_at,
	//         u.name AS user_name, u.email AS user_email
	//  FROM trip_enrollments te
	//  JOIN users u ON u.id = te.user_id
	//  WHERE te.trip_id = $1
	//  ORDER BY te.created_at
	ListTripEnrollments(ctx context.Context, tripID int64) ([]ListTripEnrollmentsRow, error)
	//ListTrips
	//
	//  SELECT id, created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, cost_total, cost_per_person, max_crew, image_logo_url, image_photo_url, image_route_url, description, status, enroll_token, created_at, updated_at FROM trips ORDER BY embark_date ASC, id ASC LIMIT $1 OFFSET $2
	ListTrips(ctx context.Context, arg ListTripsParams) ([]Trip, error)
	//ListUsers
	//
	//  SELECT id, email, name, password_hash, avatar_url, firebase_uid, role, patent_type, patent_number, created_at, updated_at FROM users ORDER BY role, name, id
	ListUsers(ctx context.Context) ([]User, error)
	//ListVoyageCrewAssignments
	//
	//  SELECT ca.id, ca.trip_id, ca.voyage_id, ca.crew_member_id, ca.role, ca.patent_number, ca.created_at,
	//         cm.full_name, cm.email
	//  FROM crew_assignments ca
	//  JOIN crew_members cm ON cm.id = ca.crew_member_id
	//  WHERE ca.voyage_id = $1
	//  ORDER BY cm.full_name
	ListVoyageCrewAssignments(ctx context.Context, voyageID types.NullInt64) ([]ListVoyageCrewAssignmentsRow, error)
	//ListVoyagePorts
	//
	//  SELECT id, voyage_id, name, latitude, longitude, position, created_at FROM voyage_ports WHERE voyage_id = $1 ORDER BY position, id
	ListVoyagePorts(ctx context.Context, voyageID int64) ([]VoyagePort, error)
	//ListVoyageVoyageOpinions
	//
	//  SELECT vo.id, vo.voyage_id, vo.crew_member_id, vo.file_path, vo.file_format, vo.created_at, cm.full_name
	//  FROM voyage_opinions vo
	//  JOIN crew_members cm ON cm.id = vo.crew_member_id
	//  WHERE vo.voyage_id = $1
	//  ORDER BY cm.full_name
	ListVoyageVoyageOpinions(ctx context.Context, voyageID int64) ([]ListVoyageVoyageOpinionsRow, error)
	//ListVoyages
	//
	//  SELECT id, created_by, cruise_id, name, year, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at FROM voyages ORDER BY year DESC, embark_date DESC, id DESC LIMIT $1 OFFSET $2
	ListVoyages(ctx context.Context, arg ListVoyagesParams) ([]Voyage, error)
	//ListYachts
	//
	//  SELECT id, created_by, name, registration_no, yacht_type, created_at, updated_at FROM yachts ORDER BY name, id LIMIT $1 OFFSET $2
	ListYachts(ctx context.Context, arg ListYachtsParams) ([]Yacht, error)
	//RepointCrewAssignmentsToVoyage
	//
	//  UPDATE crew_assignments SET voyage_id = $1, trip_id = NULL
	//  WHERE trip_id = $2
	RepointCrewAssignmentsToVoyage(ctx context.Context, arg RepointCrewAssignmentsToVoyageParams) error
	//SetCruiseEnrollToken
	//
	//  UPDATE cruises SET enroll_token = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2
	SetCruiseEnrollToken(ctx context.Context, arg SetCruiseEnrollTokenParams) error
	//SetTripEnrollToken
	//
	//  UPDATE trips SET enroll_token = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2
	SetTripEnrollToken(ctx context.Context, arg SetTripEnrollTokenParams) error
	//SetVoyagePortPosition
	//
	//  UPDATE voyage_ports SET position = $3 WHERE id = $1 AND voyage_id = $2
	SetVoyagePortPosition(ctx context.Context, arg SetVoyagePortPositionParams) error
	//UpdateCrewMember
	//
	//  UPDATE crew_members SET
	//      full_name = $1, email = $2, patent_number = $3,
	//      phone = $4, pzz_license_type = $5, pzz_license_number = $6,
	//      emergency_contact_name = $7, emergency_contact_phone = $8,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE id = $9
	UpdateCrewMember(ctx context.Context, arg UpdateCrewMemberParams) error
	//UpdateCruise
	//
	//  UPDATE cruises SET
	//      name = $1, embark_date = $2, disembark_date = $3, countries = $4,
	//      start_port = $5, end_port = $6, description = $7,
	//      image_logo_url = $8, image_photo_url = $9, image_route_url = $10,
	//      max_crew = $11, cost_per_person = $12,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE id = $13
	UpdateCruise(ctx context.Context, arg UpdateCruiseParams) error
	//UpdateCruiseEnrollmentStatus
	//
	//  UPDATE cruise_enrollments SET status = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2
	UpdateCruiseEnrollmentStatus(ctx context.Context, arg UpdateCruiseEnrollmentStatusParams) error
	//UpdateTraining
	//
	//  UPDATE trainings SET date = $1, name = $2, organizer = $3, cost = $4, url = $5, updated_at = CURRENT_TIMESTAMP WHERE id = $6 AND user_id = $7
	UpdateTraining(ctx context.Context, arg UpdateTrainingParams) error
	//UpdateTrip
	//
	//  UPDATE trips SET
	//      name = $1, embark_date = $2, disembark_date = $3, countries = $4,
	//      start_port = $5, end_port = $6, captain_name = $7, yacht_id = $8,
	//      cost_total = $9, cost_per_person = $10, max_crew = $11,
	//      image_logo_url = $12, image_photo_url = $13, image_route_url = $14, description = $15,
	//      cruise_id = $16,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE id = $17
	UpdateTrip(ctx context.Context, arg UpdateTripParams) error
	//UpdateTripEnrollmentStatus
	//
	//  UPDATE trip_enrollments SET status = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2
	UpdateTripEnrollmentStatus(ctx context.Context, arg UpdateTripEnrollmentStatusParams) error
	//UpdateUser
	//
	//  UPDATE users SET name = $1, email = $2, avatar_url = $3, updated_at = CURRENT_TIMESTAMP WHERE id = $4
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	//UpdateUserPatent
	//
	//  UPDATE users SET patent_type = $1, patent_number = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $3
	UpdateUserPatent(ctx context.Context, arg UpdateUserPatentParams) error
	//UpdateUserRole
	//
	//  UPDATE users SET role = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	//UpdateVoyage
	//
	//  UPDATE voyages SET
	//      name = $1, year = $2, embark_date = $3, disembark_date = $4, countries = $5,
	//      start_port = $6, end_port = $7, captain_name = $8, yacht_id = $9,
	//      hours_total = $10, hours_sail = $11, hours_engine = $12, hours_over_6bf = $13,
	//      miles = $14, days = $15, tidal_waters = $16,
	//      cost_total = $17, cost_per_person = $18,
	//      image_logo_url = $19, image_photo_url = $20, image_route_url = $21, description = $22,
	//      cruise_id = $23,
	//      updated_at = CURRENT_TIMESTAMP
	//  WHERE id = $24
	UpdateVoyage(ctx context.Context, arg UpdateVoyageParams) error
	//UpdateYacht
	//
	//  UPDATE yachts SET name = $1, registration_no = $2, yacht_type = $3, updated_at = CURRENT_TIMESTAMP
	//  WHERE id = $4
	UpdateYacht(ctx context.Context, arg UpdateYachtParams) error
	//UpsertUserByFirebaseUID
	//
	//  INSERT INTO users (email, name, password_hash, firebase_uid)
	//  VALUES ($1, $2, '', $3)
	//  ON CONFLICT(firebase_uid) DO UPDATE SET
	//    email = EXCLUDED.email,
	//    name = CASE WHEN EXCLUDED.name = '' THEN users.name ELSE EXCLUDED.name END,
	//    updated_at = CURRENT_TIMESTAMP
	//  RETURNING id, email, name, password_hash, avatar_url, firebase_uid, role, patent_type, patent_number, created_at, updated_at
	UpsertUserByFirebaseUID(ctx context.Context, arg UpsertUserByFirebaseUIDParams) (User, error)
	//UpsertVoyageOpinion
	//
	//  INSERT INTO voyage_opinions (voyage_id, crew_member_id, file_path, file_format)
	//  VALUES ($1, $2, $3, $4)
	//  ON CONFLICT (voyage_id, crew_member_id) DO UPDATE
	//  SET file_path = EXCLUDED.file_path, file_format = EXCLUDED.file_format, created_at = CURRENT_TIMESTAMP
	//  RETURNING id, voyage_id, crew_member_id, file_path, file_format, created_at
	UpsertVoyageOpinion(ctx context.Context, arg UpsertVoyageOpinionParams) (VoyageOpinion, error)
}

var _ Querier = (*Queries)(nil)
