// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trainings.sql

package sqlcdb

import (
	"context"

	types "github.com/marcinskalski/sailor-buddy/backend/internal/types"
)

const countTrainings = `-- name: CountTrainings :one
SELECT COUNT(*)::BIGINT FROM trainings WHERE user_id = $1
`

// CountTrainings
//
//	SELECT COUNT(*)::BIGINT FROM trainings WHERE user_id = $1
func (q *Queries) CountTrainings(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrainings, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTraining = `-- name: CreateTraining :one
INSERT INTO trainings (user_id, date, name, organizer, cost, url) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, date, name, organizer, cost, url, created_at, updated_at
`

type CreateTrainingParams struct {
	UserID    int64             `json:"user_id"`
	Date      types.NullString  `json:"date"`
	Name      string            `json:"name"`
	Organizer types.NullString  `json:"organizer"`
	Cost      types.NullFloat64 `json:"cost"`
	Url       types.NullString  `json:"url"`
}

// CreateTraining
//
//	INSERT INTO trainings (user_id, date, name, organizer, cost, url) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, date, name, organizer, cost, url, created_at, updated_at
func (q *Queries) CreateTraining(ctx context.Context, arg CreateTrainingParams) (Training, error) {
	row := q.db.QueryRowContext(ctx, createTraining,
		arg.UserID,
		arg.Date,
		arg.Name,
		arg.Organizer,
		arg.Cost,
		arg.Url,
	)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Name,
		&i.Organizer,
		&i.Cost,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTraining = `-- name: DeleteTraining :exec
DELETE FROM trainings WHERE id = $1 AND user_id = $2
`

type DeleteTrainingParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// DeleteTraining
//
//	DELETE FROM trainings WHERE id = $1 AND user_id = $2
func (q *Queries) DeleteTraining(ctx context.Context, arg DeleteTrainingParams) error {
	_, err := q.db.ExecContext(ctx, deleteTraining, arg.ID, arg.UserID)
	return err
}

const getTraining = `-- name: GetTraining :one
SELECT id, user_id, date, name, organizer, cost, url, created_at, updated_at FROM trainings WHERE id = $1 AND user_id = $2
`

type GetTrainingParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// GetTraining
//
//	SELECT id, user_id, date, name, organizer, cost, url, created_at, updated_at FROM trainings WHERE id = $1 AND user_id = $2
func (q *Queries) GetTraining(ctx context.Context, arg GetTrainingParams) (Training, error) {
	row := q.db.QueryRowContext(ctx, getTraining, arg.ID, arg.UserID)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.Name,
		&i.Organizer,
		&i.Cost,
		&i.Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTrainings = `-- name: ListTrainings :many
SELECT id, user_id, date, name, organizer, cost, url, created_at, updated_at FROM trainings WHERE user_id = $1 ORDER BY date DESC, id DESC LIMIT $2 OFFSET $3
`

type ListTrainingsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// ListTrainings
//
//	SELECT id, user_id, date, name, organizer, cost, url, created_at, updated_at FROM trainings WHERE user_id = $1 ORDER BY date DESC, id DESC LIMIT $2 OFFSET $3
func (q *Queries) ListTrainings(ctx context.Context, arg ListTrainingsParams) ([]Training, error) {
	rows, err := q.db.QueryContext(ctx, listTrainings, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Training
	for rows.Next() {
		var i Training
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.Name,
			&i.Organizer,
			&i.Cost,
			&i.Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTraining = `-- name: UpdateTraining :exec
UPDATE trainings SET date = $1, name = $2, organizer = $3, cost = $4, url = $5, updated_at = CURRENT_TIMESTAMP WHERE id = $6 AND user_id = $7
`

type UpdateTrainingParams struct {
	Date      types.NullString  `json:"date"`
	Name      string            `json:"name"`
	Organizer types.NullString  `json:"organizer"`
	Cost      types.NullFloat64 `json:"cost"`
	Url       types.NullString  `json:"url"`
	ID        int64             `json:"id"`
	UserID    int64             `json:"user_id"`
}

// UpdateTraining
//
//	UPDATE trainings SET date = $1, name = $2, organizer = $3, cost = $4, url = $5, updated_at = CURRENT_TIMESTAMP WHERE id = $6 AND user_id = $7
func (q *Queries) UpdateTraining(ctx context.Context, arg UpdateTrainingParams) error {
	_, err := q.db.ExecContext(ctx, updateTraining,
		arg.Date,
		arg.Name,
		arg.Organizer,
		arg.Cost,
		arg.Url,
		arg.ID,
		arg.UserID,
	)
	return err
}
