// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trips.sql

package sqlcdb

import (
	"context"

	types "github.com/marcinskalski/sailor-buddy/backend/internal/types"
)

const cancelTrip = `-- name: CancelTrip :one
UPDATE trips SET status = 'cancelled', enroll_token = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status = 'planned' RETURNING id, created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, cost_total, cost_per_person, max_crew, image_logo_url, image_photo_url, image_route_url, description, status, enroll_token, created_at, updated_at
`

// CancelTrip
//
//	UPDATE trips SET status = 'cancelled', enroll_token = NULL, updated_at = CURRENT_TIMESTAMP
//	WHERE id = $1 AND status = 'planned' RETURNING id, created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, cost_total, cost_per_person, max_crew, image_logo_url, image_photo_url, image_route_url, description, status, enroll_token, created_at, updated_at
func (q *Queries) CancelTrip(ctx context.Context, id int64) (Trip, error) {
	row := q.db.QueryRowContext(ctx, cancelTrip, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CruiseID,
		&i.Name,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.CaptainName,
		&i.YachtID,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.MaxCrew,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.Status,
		&i.EnrollToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const clearTripEnrollToken = `-- name: ClearTripEnrollToken :exec
UPDATE trips SET enroll_token = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

// ClearTripEnrollToken
//
//	UPDATE trips SET enroll_token = NULL, updated_at = CURRENT_TIMESTAMP WHERE id = $1
func (q *Queries) ClearTripEnrollToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearTripEnrollToken, id)
	return err
}

const countTrips = `-- name: CountTrips :one
SELECT COUNT(*)::BIGINT FROM trips
`

// CountTrips
//
//	SELECT COUNT(*)::BIGINT FROM trips
func (q *Queries) CountTrips(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTrips)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (
    created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port,
    captain_name, yacht_id, cost_total, cost_per_person, max_crew,
    image_logo_url, image_photo_url, image_route_url, description, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) RETURNING id, created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, cost_total, cost_per_person, max_crew, image_logo_url, image_photo_url, image_route_url, description, status, enroll_token, created_at, updated_at
`

type CreateTripParams struct {
	CreatedBy     types.NullInt64   `json:"created_by"`
	CruiseID      types.NullInt64   `json:"cruise_id"`
	Name          string            `json:"name"`
	EmbarkDate    types.NullString  `json:"embark_date"`
	DisembarkDate types.NullString  `json:"disembark_date"`
	Countries     types.NullString  `json:"countries"`
	StartPort     types.NullString  `json:"start_port"`
	EndPort       types.NullString  `json:"end_port"`
	CaptainName   types.NullString  `json:"captain_name"`
	YachtID       types.NullInt64   `json:"yacht_id"`
	CostTotal     types.NullFloat64 `json:"cost_total"`
	CostPerPerson types.NullFloat64 `json:"cost_per_person"`
	MaxCrew       types.NullInt64   `json:"max_crew"`
	ImageLogoUrl  types.NullString  `json:"image_logo_url"`
	ImagePhotoUrl types.NullString  `json:"image_photo_url"`
	ImageRouteUrl types.NullString  `json:"image_route_url"`
	Description   types.NullString  `json:"description"`
	Status        TripStatus        `json:"status"`
}

// CreateTrip
//
//	INSERT INTO trips (
//	    created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port,
//	    captain_name, yacht_id, cost_total, cost_per_person, max_crew,
//	    image_logo_url, image_photo_url, image_route_url, description, status
//	) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) RETURNING id, created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, cost_total, cost_per_person, max_crew, image_logo_url, image_photo_url, image_route_url, description, status, enroll_token, created_at, updated_at
func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRowContext(ctx, createTrip,
		arg.CreatedBy,
		arg.CruiseID,
		arg.Name,
		arg.EmbarkDate,
		arg.DisembarkDate,
		arg.Countries,
		arg.StartPort,
		arg.EndPort,
		arg.CaptainName,
		arg.YachtID,
		arg.CostTotal,
		arg.CostPerPerson,
		arg.MaxCrew,
		arg.ImageLogoUrl,
		arg.ImagePhotoUrl,
		arg.ImageRouteUrl,
		arg.Description,
		arg.Status,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CruiseID,
		&i.Name,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.CaptainName,
		&i.YachtID,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.MaxCrew,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.Status,
		&i.EnrollToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTrip = `-- name: DeleteTrip :exec
DELETE FROM trips WHERE id = $1
`

// DeleteTrip
//
//	DELETE FROM trips WHERE id = $1
func (q *Queries) DeleteTrip(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrip, id)
	return err
}

const getTrip = `-- name: GetTrip :one
SELECT id, created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, cost_total, cost_per_person, max_crew, image_logo_url, image_photo_url, image_route_url, description, status, enroll_token, created_at, updated_at FROM trips WHERE id = $1
`

// GetTrip
//
//	SELECT id, created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, cost_total, cost_per_person, max_crew, image_logo_url, image_photo_url, image_route_url, description, status, enroll_token, created_at, updated_at FROM trips WHERE id = $1
func (q *Queries) GetTrip(ctx context.Context, id int64) (Trip, error) {
	row := q.db.QueryRowContext(ctx, getTrip, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.CruiseID,
		&i.Name,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.CaptainName,
		&i.YachtID,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.MaxCrew,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.Status,
		&i.EnrollToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTripByEnrollToken = `-- name: GetTripByEnrollToken :one
SELECT id, name, embark_date, disembark_date, countries, start_port, end_port,
       description, max_crew, captain_name, image_photo_url
FROM trips WHERE enroll_token = $1
`

type GetTripByEnrollTokenRow struct {
	ID            int64            `json:"id"`
	Name          string           `json:"name"`
	EmbarkDate    types.NullString `json:"embark_date"`
	DisembarkDate types.NullString `json:"disembark_date"`
	Countries     types.NullString `json:"countries"`
	StartPort     types.NullString `json:"start_port"`
	EndPort       types.NullString `json:"end_port"`
	Description   types.NullString `json:"description"`
	MaxCrew       types.NullInt64  `json:"max_crew"`
	CaptainName   types.NullString `json:"captain_name"`
	ImagePhotoUrl types.NullString `json:"image_photo_url"`
}

// GetTripByEnrollToken
//
//	SELECT id, name, embark_date, disembark_date, countries, start_port, end_port,
//	       description, max_crew, captain_name, image_photo_url
//	FROM trips WHERE enroll_token = $1
func (q *Queries) GetTripByEnrollToken(ctx context.Context, enrollToken types.NullString) (GetTripByEnrollTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getTripByEnrollToken, enrollToken)
	var i GetTripByEnrollTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.Description,
		&i.MaxCrew,
		&i.CaptainName,
		&i.ImagePhotoUrl,
	)
	return i, err
}

const getTripStatus = `-- name: GetTripStatus :one
SELECT status FROM trips WHERE id = $1
`

// GetTripStatus
//
//	SELECT status FROM trips WHERE id = $1
func (q *Queries) GetTripStatus(ctx context.Context, id int64) (TripStatus, error) {
	row := q.db.QueryRowContext(ctx, getTripStatus, id)
	var status TripStatus
	err := row.Scan(&status)
	return status, err
}

const listTrips = `-- name: ListTrips :many
SELECT id, created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, cost_total, cost_per_person, max_crew, image_logo_url, image_photo_url, image_route_url, description, status, enroll_token, created_at, updated_at FROM trips ORDER BY embark_date ASC, id ASC LIMIT $1 OFFSET $2
`

type ListTripsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// ListTrips
//
//	SELECT id, created_by, cruise_id, name, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, cost_total, cost_per_person, max_crew, image_logo_url, image_photo_url, image_route_url, description, status, enroll_token, created_at, updated_at FROM trips ORDER BY embark_date ASC, id ASC LIMIT $1 OFFSET $2
func (q *Queries) ListTrips(ctx context.Context, arg ListTripsParams) ([]Trip, error) {
	rows, err := q.db.QueryContext(ctx, listTrips, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.CruiseID,
			&i.Name,
			&i.EmbarkDate,
			&i.DisembarkDate,
			&i.Countries,
			&i.StartPort,
			&i.EndPort,
			&i.CaptainName,
			&i.YachtID,
			&i.CostTotal,
			&i.CostPerPerson,
			&i.MaxCrew,
			&i.ImageLogoUrl,
			&i.ImagePhotoUrl,
			&i.ImageRouteUrl,
			&i.Description,
			&i.Status,
			&i.EnrollToken,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTripEnrollToken = `-- name: SetTripEnrollToken :exec
UPDATE trips SET enroll_token = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2
`

type SetTripEnrollTokenParams struct {
	EnrollToken types.NullString `json:"enroll_token"`
	ID          int64            `json:"id"`
}

// SetTripEnrollToken
//
//	UPDATE trips SET enroll_token = $1, updated_at = CURRENT_TIMESTAMP WHERE id = $2
func (q *Queries) SetTripEnrollToken(ctx context.Context, arg SetTripEnrollTokenParams) error {
	_, err := q.db.ExecContext(ctx, setTripEnrollToken, arg.EnrollToken, arg.ID)
	return err
}

const updateTrip = `-- name: UpdateTrip :exec
UPDATE trips SET
    name = $1, embark_date = $2, disembark_date = $3, countries = $4,
    start_port = $5, end_port = $6, captain_name = $7, yacht_id = $8,
    cost_total = $9, cost_per_person = $10, max_crew = $11,
    image_logo_url = $12, image_photo_url = $13, image_route_url = $14, description = $15,
    cruise_id = $16,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $17
`

type UpdateTripParams struct {
	Name          string            `json:"name"`
	EmbarkDate    types.NullString  `json:"embark_date"`
	DisembarkDate types.NullString  `json:"disembark_date"`
	Countries     types.NullString  `json:"countries"`
	StartPort     types.NullString  `json:"start_port"`
	EndPort       types.NullString  `json:"end_port"`
	CaptainName   types.NullString  `json:"captain_name"`
	YachtID       types.NullInt64   `json:"yacht_id"`
	CostTotal     types.NullFloat64 `json:"cost_total"`
	CostPerPerson types.NullFloat64 `json:"cost_per_person"`
	MaxCrew       types.NullInt64   `json:"max_crew"`
	ImageLogoUrl  types.NullString  `json:"image_logo_url"`
	ImagePhotoUrl types.NullString  `json:"image_photo_url"`
	ImageRouteUrl types.NullString  `json:"image_route_url"`
	Description   types.NullString  `json:"description"`
	CruiseID      types.NullInt64   `json:"cruise_id"`
	ID            int64             `json:"id"`
}

// UpdateTrip
//
//	UPDATE trips SET
//	    name = $1, embark_date = $2, disembark_date = $3, countries = $4,
//	    start_port = $5, end_port = $6, captain_name = $7, yacht_id = $8,
//	    cost_total = $9, cost_per_person = $10, max_crew = $11,
//	    image_logo_url = $12, image_photo_url = $13, image_route_url = $14, description = $15,
//	    cruise_id = $16,
//	    updated_at = CURRENT_TIMESTAMP
//	WHERE id = $17
func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) error {
	_, err := q.db.ExecContext(ctx, updateTrip,
		arg.Name,
		arg.EmbarkDate,
		arg.DisembarkDate,
		arg.Countries,
		arg.StartPort,
		arg.EndPort,
		arg.CaptainName,
		arg.YachtID,
		arg.CostTotal,
		arg.CostPerPerson,
		arg.MaxCrew,
		arg.ImageLogoUrl,
		arg.ImagePhotoUrl,
		arg.ImageRouteUrl,
		arg.Description,
		arg.CruiseID,
		arg.ID,
	)
	return err
}
