// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcdb

import (
	"context"

	types "github.com/marcinskalski/sailor-buddy/backend/internal/types"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash, firebase_uid) VALUES ($1, $2, '', $3) RETURNING id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid, patent_type, patent_number
`

type CreateUserParams struct {
	Email       string           `json:"email"`
	Name        string           `json:"name"`
	FirebaseUid types.NullString `json:"firebase_uid"`
}

// CreateUser
//
//	INSERT INTO users (email, name, password_hash, firebase_uid) VALUES ($1, $2, '', $3) RETURNING id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid, patent_type, patent_number
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Name, arg.FirebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirebaseUid,
		&i.PatentType,
		&i.PatentNumber,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid, patent_type, patent_number FROM users WHERE email = $1
`

// GetUserByEmail
//
//	SELECT id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid, patent_type, patent_number FROM users WHERE email = $1
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirebaseUid,
		&i.PatentType,
		&i.PatentNumber,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid, patent_type, patent_number FROM users WHERE firebase_uid = $1
`

// GetUserByFirebaseUID
//
//	SELECT id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid, patent_type, patent_number FROM users WHERE firebase_uid = $1
func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid types.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirebaseUid,
		&i.PatentType,
		&i.PatentNumber,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid, patent_type, patent_number FROM users WHERE id = $1
`

// GetUserByID
//
//	SELECT id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid, patent_type, patent_number FROM users WHERE id = $1
func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirebaseUid,
		&i.PatentType,
		&i.PatentNumber,
	)
	return i, err
}

const linkFirebaseUIDByEmail = `-- name: LinkFirebaseUIDByEmail :one
UPDATE users SET
  firebase_uid = $1,
  name = COALESCE(NULLIF($2::TEXT, ''), name),
  updated_at = CURRENT_TIMESTAMP
WHERE email = $3
  AND (firebase_uid IS NULL OR firebase_uid = $1)
RETURNING id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid, patent_type, patent_number
`

type LinkFirebaseUIDByEmailParams struct {
	FirebaseUid types.NullString `json:"firebase_uid"`
	NewName     string           `json:"new_name"`
	Email       string           `json:"email"`
}

// LinkFirebaseUIDByEmail
//
//	UPDATE users SET
//	  firebase_uid = $1,
//	  name = COALESCE(NULLIF($2::TEXT, ''), name),
//	  updated_at = CURRENT_TIMESTAMP
//	WHERE email = $3
//	  AND (firebase_uid IS NULL OR firebase_uid = $1)
//	RETURNING id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid, patent_type, patent_number
func (q *Queries) LinkFirebaseUIDByEmail(ctx context.Context, arg LinkFirebaseUIDByEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, linkFirebaseUIDByEmail, arg.FirebaseUid, arg.NewName, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirebaseUid,
		&i.PatentType,
		&i.PatentNumber,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET name = $1, email = $2, avatar_url = $3, updated_at = CURRENT_TIMESTAMP WHERE id = $4
`

type UpdateUserParams struct {
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	AvatarUrl types.NullString `json:"avatar_url"`
	ID        int64            `json:"id"`
}

// UpdateUser
//
//	UPDATE users SET name = $1, email = $2, avatar_url = $3, updated_at = CURRENT_TIMESTAMP WHERE id = $4
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
		arg.ID,
	)
	return err
}

const updateUserPatent = `-- name: UpdateUserPatent :exec
UPDATE users SET patent_type = $1, patent_number = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $3
`

type UpdateUserPatentParams struct {
	PatentType   types.NullString `json:"patent_type"`
	PatentNumber types.NullString `json:"patent_number"`
	ID           int64            `json:"id"`
}

// UpdateUserPatent
//
//	UPDATE users SET patent_type = $1, patent_number = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $3
func (q *Queries) UpdateUserPatent(ctx context.Context, arg UpdateUserPatentParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPatent, arg.PatentType, arg.PatentNumber, arg.ID)
	return err
}

const upsertUserByFirebaseUID = `-- name: UpsertUserByFirebaseUID :one
INSERT INTO users (email, name, password_hash, firebase_uid)
VALUES ($1, $2, '', $3)
ON CONFLICT(firebase_uid) DO UPDATE SET
  email = EXCLUDED.email,
  name = CASE WHEN EXCLUDED.name = '' THEN users.name ELSE EXCLUDED.name END,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid, patent_type, patent_number
`

type UpsertUserByFirebaseUIDParams struct {
	Email       string           `json:"email"`
	Name        string           `json:"name"`
	FirebaseUid types.NullString `json:"firebase_uid"`
}

// UpsertUserByFirebaseUID
//
//	INSERT INTO users (email, name, password_hash, firebase_uid)
//	VALUES ($1, $2, '', $3)
//	ON CONFLICT(firebase_uid) DO UPDATE SET
//	  email = EXCLUDED.email,
//	  name = CASE WHEN EXCLUDED.name = '' THEN users.name ELSE EXCLUDED.name END,
//	  updated_at = CURRENT_TIMESTAMP
//	RETURNING id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid, patent_type, patent_number
func (q *Queries) UpsertUserByFirebaseUID(ctx context.Context, arg UpsertUserByFirebaseUIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUserByFirebaseUID, arg.Email, arg.Name, arg.FirebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirebaseUid,
		&i.PatentType,
		&i.PatentNumber,
	)
	return i, err
}
