// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash, firebase_uid) VALUES (?, ?, '', ?) RETURNING id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid
`

type CreateUserParams struct {
	Email       string
	Name        string
	FirebaseUid sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Name, arg.FirebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirebaseUid,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirebaseUid,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid FROM users WHERE firebase_uid = ?
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirebaseUid,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirebaseUid,
	)
	return i, err
}

const linkFirebaseUIDByEmail = `-- name: LinkFirebaseUIDByEmail :one
UPDATE users SET
  firebase_uid = ?1,
  name = CASE WHEN ?2 = '' THEN name ELSE ?2 END,
  updated_at = CURRENT_TIMESTAMP
WHERE email = ?3
RETURNING id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid
`

type LinkFirebaseUIDByEmailParams struct {
	FirebaseUid sql.NullString
	NewName     interface{}
	Email       string
}

func (q *Queries) LinkFirebaseUIDByEmail(ctx context.Context, arg LinkFirebaseUIDByEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, linkFirebaseUIDByEmail, arg.FirebaseUid, arg.NewName, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirebaseUid,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET name = ?, email = ?, avatar_url = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateUserParams struct {
	Name      string
	Email     string
	AvatarUrl sql.NullString
	ID        int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
		arg.ID,
	)
	return err
}

const upsertUserByFirebaseUID = `-- name: UpsertUserByFirebaseUID :one
INSERT INTO users (email, name, password_hash, firebase_uid)
VALUES (?, ?, '', ?)
ON CONFLICT(firebase_uid) DO UPDATE SET
  email = excluded.email,
  name = CASE WHEN excluded.name = '' THEN users.name ELSE excluded.name END,
  updated_at = CURRENT_TIMESTAMP
RETURNING id, email, name, password_hash, avatar_url, created_at, updated_at, firebase_uid
`

type UpsertUserByFirebaseUIDParams struct {
	Email       string
	Name        string
	FirebaseUid sql.NullString
}

func (q *Queries) UpsertUserByFirebaseUID(ctx context.Context, arg UpsertUserByFirebaseUIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUserByFirebaseUID, arg.Email, arg.Name, arg.FirebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirebaseUid,
	)
	return i, err
}
