// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voyages.sql

package sqlcdb

import (
	"context"

	types "github.com/marcinskalski/sailor-buddy/backend/internal/types"
)

const createOrgVoyage = `-- name: CreateOrgVoyage :one
INSERT INTO voyages (
    owner_id, org_id, cruise_id, name, year, embark_date, disembark_date, countries, start_port, end_port,
    captain_name, yacht_id,
    hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, tidal_waters,
    cost_total, cost_per_person,
    image_logo_url, image_photo_url, image_route_url, description
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25) RETURNING id, owner_id, org_id, name, year, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, cruise_id
`

type CreateOrgVoyageParams struct {
	OwnerID       int64             `json:"owner_id"`
	OrgID         types.NullInt64   `json:"org_id"`
	CruiseID      types.NullInt64   `json:"cruise_id"`
	Name          string            `json:"name"`
	Year          types.NullInt64   `json:"year"`
	EmbarkDate    types.NullString  `json:"embark_date"`
	DisembarkDate types.NullString  `json:"disembark_date"`
	Countries     types.NullString  `json:"countries"`
	StartPort     types.NullString  `json:"start_port"`
	EndPort       types.NullString  `json:"end_port"`
	CaptainName   types.NullString  `json:"captain_name"`
	YachtID       types.NullInt64   `json:"yacht_id"`
	HoursTotal    float64           `json:"hours_total"`
	HoursSail     float64           `json:"hours_sail"`
	HoursEngine   float64           `json:"hours_engine"`
	HoursOver6bf  float64           `json:"hours_over_6bf"`
	Miles         float64           `json:"miles"`
	Days          int64             `json:"days"`
	TidalWaters   int64             `json:"tidal_waters"`
	CostTotal     types.NullFloat64 `json:"cost_total"`
	CostPerPerson types.NullFloat64 `json:"cost_per_person"`
	ImageLogoUrl  types.NullString  `json:"image_logo_url"`
	ImagePhotoUrl types.NullString  `json:"image_photo_url"`
	ImageRouteUrl types.NullString  `json:"image_route_url"`
	Description   types.NullString  `json:"description"`
}

func (q *Queries) CreateOrgVoyage(ctx context.Context, arg CreateOrgVoyageParams) (Voyage, error) {
	row := q.db.QueryRowContext(ctx, createOrgVoyage,
		arg.OwnerID,
		arg.OrgID,
		arg.CruiseID,
		arg.Name,
		arg.Year,
		arg.EmbarkDate,
		arg.DisembarkDate,
		arg.Countries,
		arg.StartPort,
		arg.EndPort,
		arg.CaptainName,
		arg.YachtID,
		arg.HoursTotal,
		arg.HoursSail,
		arg.HoursEngine,
		arg.HoursOver6bf,
		arg.Miles,
		arg.Days,
		arg.TidalWaters,
		arg.CostTotal,
		arg.CostPerPerson,
		arg.ImageLogoUrl,
		arg.ImagePhotoUrl,
		arg.ImageRouteUrl,
		arg.Description,
	)
	var i Voyage
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.OrgID,
		&i.Name,
		&i.Year,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.CaptainName,
		&i.YachtID,
		&i.HoursTotal,
		&i.HoursSail,
		&i.HoursEngine,
		&i.HoursOver6bf,
		&i.Miles,
		&i.Days,
		&i.TidalWaters,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CruiseID,
	)
	return i, err
}

const createVoyage = `-- name: CreateVoyage :one
INSERT INTO voyages (
    owner_id, name, year, embark_date, disembark_date, countries, start_port, end_port,
    captain_name, yacht_id,
    hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, tidal_waters,
    cost_total, cost_per_person,
    image_logo_url, image_photo_url, image_route_url, description
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23) RETURNING id, owner_id, org_id, name, year, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, cruise_id
`

type CreateVoyageParams struct {
	OwnerID       int64             `json:"owner_id"`
	Name          string            `json:"name"`
	Year          types.NullInt64   `json:"year"`
	EmbarkDate    types.NullString  `json:"embark_date"`
	DisembarkDate types.NullString  `json:"disembark_date"`
	Countries     types.NullString  `json:"countries"`
	StartPort     types.NullString  `json:"start_port"`
	EndPort       types.NullString  `json:"end_port"`
	CaptainName   types.NullString  `json:"captain_name"`
	YachtID       types.NullInt64   `json:"yacht_id"`
	HoursTotal    float64           `json:"hours_total"`
	HoursSail     float64           `json:"hours_sail"`
	HoursEngine   float64           `json:"hours_engine"`
	HoursOver6bf  float64           `json:"hours_over_6bf"`
	Miles         float64           `json:"miles"`
	Days          int64             `json:"days"`
	TidalWaters   int64             `json:"tidal_waters"`
	CostTotal     types.NullFloat64 `json:"cost_total"`
	CostPerPerson types.NullFloat64 `json:"cost_per_person"`
	ImageLogoUrl  types.NullString  `json:"image_logo_url"`
	ImagePhotoUrl types.NullString  `json:"image_photo_url"`
	ImageRouteUrl types.NullString  `json:"image_route_url"`
	Description   types.NullString  `json:"description"`
}

func (q *Queries) CreateVoyage(ctx context.Context, arg CreateVoyageParams) (Voyage, error) {
	row := q.db.QueryRowContext(ctx, createVoyage,
		arg.OwnerID,
		arg.Name,
		arg.Year,
		arg.EmbarkDate,
		arg.DisembarkDate,
		arg.Countries,
		arg.StartPort,
		arg.EndPort,
		arg.CaptainName,
		arg.YachtID,
		arg.HoursTotal,
		arg.HoursSail,
		arg.HoursEngine,
		arg.HoursOver6bf,
		arg.Miles,
		arg.Days,
		arg.TidalWaters,
		arg.CostTotal,
		arg.CostPerPerson,
		arg.ImageLogoUrl,
		arg.ImagePhotoUrl,
		arg.ImageRouteUrl,
		arg.Description,
	)
	var i Voyage
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.OrgID,
		&i.Name,
		&i.Year,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.CaptainName,
		&i.YachtID,
		&i.HoursTotal,
		&i.HoursSail,
		&i.HoursEngine,
		&i.HoursOver6bf,
		&i.Miles,
		&i.Days,
		&i.TidalWaters,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CruiseID,
	)
	return i, err
}

const deleteOrgVoyage = `-- name: DeleteOrgVoyage :exec
DELETE FROM voyages WHERE id = $1 AND org_id = $2
`

type DeleteOrgVoyageParams struct {
	ID    int64           `json:"id"`
	OrgID types.NullInt64 `json:"org_id"`
}

func (q *Queries) DeleteOrgVoyage(ctx context.Context, arg DeleteOrgVoyageParams) error {
	_, err := q.db.ExecContext(ctx, deleteOrgVoyage, arg.ID, arg.OrgID)
	return err
}

const deleteVoyage = `-- name: DeleteVoyage :exec
DELETE FROM voyages WHERE id = $1 AND owner_id = $2 AND org_id IS NULL
`

type DeleteVoyageParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) DeleteVoyage(ctx context.Context, arg DeleteVoyageParams) error {
	_, err := q.db.ExecContext(ctx, deleteVoyage, arg.ID, arg.OwnerID)
	return err
}

const getDashboardStats = `-- name: GetDashboardStats :one
SELECT
    COUNT(*)::BIGINT AS voyage_count,
    COALESCE(SUM(hours_total), 0)::DOUBLE PRECISION AS total_hours,
    COALESCE(SUM(miles), 0)::DOUBLE PRECISION AS total_miles,
    COALESCE(SUM(days), 0)::BIGINT AS total_days,
    COALESCE(SUM(hours_sail), 0)::DOUBLE PRECISION AS total_hours_sail,
    COALESCE(SUM(hours_engine), 0)::DOUBLE PRECISION AS total_hours_engine
FROM voyages WHERE owner_id = $1 AND org_id IS NULL
`

type GetDashboardStatsRow struct {
	VoyageCount      int64   `json:"voyage_count"`
	TotalHours       float64 `json:"total_hours"`
	TotalMiles       float64 `json:"total_miles"`
	TotalDays        int64   `json:"total_days"`
	TotalHoursSail   float64 `json:"total_hours_sail"`
	TotalHoursEngine float64 `json:"total_hours_engine"`
}

func (q *Queries) GetDashboardStats(ctx context.Context, ownerID int64) (GetDashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardStats, ownerID)
	var i GetDashboardStatsRow
	err := row.Scan(
		&i.VoyageCount,
		&i.TotalHours,
		&i.TotalMiles,
		&i.TotalDays,
		&i.TotalHoursSail,
		&i.TotalHoursEngine,
	)
	return i, err
}

const getOrgDashboardStats = `-- name: GetOrgDashboardStats :one
SELECT
    COUNT(*)::BIGINT AS voyage_count,
    COALESCE(SUM(hours_total), 0)::DOUBLE PRECISION AS total_hours,
    COALESCE(SUM(miles), 0)::DOUBLE PRECISION AS total_miles,
    COALESCE(SUM(days), 0)::BIGINT AS total_days,
    COALESCE(SUM(hours_sail), 0)::DOUBLE PRECISION AS total_hours_sail,
    COALESCE(SUM(hours_engine), 0)::DOUBLE PRECISION AS total_hours_engine
FROM voyages WHERE org_id = $1
`

type GetOrgDashboardStatsRow struct {
	VoyageCount      int64   `json:"voyage_count"`
	TotalHours       float64 `json:"total_hours"`
	TotalMiles       float64 `json:"total_miles"`
	TotalDays        int64   `json:"total_days"`
	TotalHoursSail   float64 `json:"total_hours_sail"`
	TotalHoursEngine float64 `json:"total_hours_engine"`
}

func (q *Queries) GetOrgDashboardStats(ctx context.Context, orgID types.NullInt64) (GetOrgDashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getOrgDashboardStats, orgID)
	var i GetOrgDashboardStatsRow
	err := row.Scan(
		&i.VoyageCount,
		&i.TotalHours,
		&i.TotalMiles,
		&i.TotalDays,
		&i.TotalHoursSail,
		&i.TotalHoursEngine,
	)
	return i, err
}

const getOrgVoyage = `-- name: GetOrgVoyage :one
SELECT id, owner_id, org_id, name, year, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, cruise_id FROM voyages WHERE id = $1 AND org_id = $2
`

type GetOrgVoyageParams struct {
	ID    int64           `json:"id"`
	OrgID types.NullInt64 `json:"org_id"`
}

func (q *Queries) GetOrgVoyage(ctx context.Context, arg GetOrgVoyageParams) (Voyage, error) {
	row := q.db.QueryRowContext(ctx, getOrgVoyage, arg.ID, arg.OrgID)
	var i Voyage
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.OrgID,
		&i.Name,
		&i.Year,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.CaptainName,
		&i.YachtID,
		&i.HoursTotal,
		&i.HoursSail,
		&i.HoursEngine,
		&i.HoursOver6bf,
		&i.Miles,
		&i.Days,
		&i.TidalWaters,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CruiseID,
	)
	return i, err
}

const getOrgVoyagesByYear = `-- name: GetOrgVoyagesByYear :many
SELECT
    year,
    COUNT(*)::BIGINT AS voyage_count,
    COALESCE(SUM(hours_total), 0)::DOUBLE PRECISION AS total_hours,
    COALESCE(SUM(miles), 0)::DOUBLE PRECISION AS total_miles,
    COALESCE(SUM(days), 0)::BIGINT AS total_days
FROM voyages WHERE org_id = $1 GROUP BY year ORDER BY year
`

type GetOrgVoyagesByYearRow struct {
	Year        types.NullInt64 `json:"year"`
	VoyageCount int64           `json:"voyage_count"`
	TotalHours  float64         `json:"total_hours"`
	TotalMiles  float64         `json:"total_miles"`
	TotalDays   int64           `json:"total_days"`
}

func (q *Queries) GetOrgVoyagesByYear(ctx context.Context, orgID types.NullInt64) ([]GetOrgVoyagesByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrgVoyagesByYear, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrgVoyagesByYearRow
	for rows.Next() {
		var i GetOrgVoyagesByYearRow
		if err := rows.Scan(
			&i.Year,
			&i.VoyageCount,
			&i.TotalHours,
			&i.TotalMiles,
			&i.TotalDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoyage = `-- name: GetVoyage :one
SELECT id, owner_id, org_id, name, year, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, cruise_id FROM voyages WHERE id = $1 AND owner_id = $2 AND org_id IS NULL
`

type GetVoyageParams struct {
	ID      int64 `json:"id"`
	OwnerID int64 `json:"owner_id"`
}

func (q *Queries) GetVoyage(ctx context.Context, arg GetVoyageParams) (Voyage, error) {
	row := q.db.QueryRowContext(ctx, getVoyage, arg.ID, arg.OwnerID)
	var i Voyage
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.OrgID,
		&i.Name,
		&i.Year,
		&i.EmbarkDate,
		&i.DisembarkDate,
		&i.Countries,
		&i.StartPort,
		&i.EndPort,
		&i.CaptainName,
		&i.YachtID,
		&i.HoursTotal,
		&i.HoursSail,
		&i.HoursEngine,
		&i.HoursOver6bf,
		&i.Miles,
		&i.Days,
		&i.TidalWaters,
		&i.CostTotal,
		&i.CostPerPerson,
		&i.ImageLogoUrl,
		&i.ImagePhotoUrl,
		&i.ImageRouteUrl,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CruiseID,
	)
	return i, err
}

const getVoyagesByYear = `-- name: GetVoyagesByYear :many
SELECT
    year,
    COUNT(*)::BIGINT AS voyage_count,
    COALESCE(SUM(hours_total), 0)::DOUBLE PRECISION AS total_hours,
    COALESCE(SUM(miles), 0)::DOUBLE PRECISION AS total_miles,
    COALESCE(SUM(days), 0)::BIGINT AS total_days
FROM voyages WHERE owner_id = $1 AND org_id IS NULL GROUP BY year ORDER BY year
`

type GetVoyagesByYearRow struct {
	Year        types.NullInt64 `json:"year"`
	VoyageCount int64           `json:"voyage_count"`
	TotalHours  float64         `json:"total_hours"`
	TotalMiles  float64         `json:"total_miles"`
	TotalDays   int64           `json:"total_days"`
}

func (q *Queries) GetVoyagesByYear(ctx context.Context, ownerID int64) ([]GetVoyagesByYearRow, error) {
	rows, err := q.db.QueryContext(ctx, getVoyagesByYear, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVoyagesByYearRow
	for rows.Next() {
		var i GetVoyagesByYearRow
		if err := rows.Scan(
			&i.Year,
			&i.VoyageCount,
			&i.TotalHours,
			&i.TotalMiles,
			&i.TotalDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgVoyages = `-- name: ListOrgVoyages :many
SELECT id, owner_id, org_id, name, year, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, cruise_id FROM voyages WHERE org_id = $1 ORDER BY year DESC, embark_date DESC
`

func (q *Queries) ListOrgVoyages(ctx context.Context, orgID types.NullInt64) ([]Voyage, error) {
	rows, err := q.db.QueryContext(ctx, listOrgVoyages, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Voyage
	for rows.Next() {
		var i Voyage
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.OrgID,
			&i.Name,
			&i.Year,
			&i.EmbarkDate,
			&i.DisembarkDate,
			&i.Countries,
			&i.StartPort,
			&i.EndPort,
			&i.CaptainName,
			&i.YachtID,
			&i.HoursTotal,
			&i.HoursSail,
			&i.HoursEngine,
			&i.HoursOver6bf,
			&i.Miles,
			&i.Days,
			&i.TidalWaters,
			&i.CostTotal,
			&i.CostPerPerson,
			&i.ImageLogoUrl,
			&i.ImagePhotoUrl,
			&i.ImageRouteUrl,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CruiseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoyages = `-- name: ListVoyages :many
SELECT id, owner_id, org_id, name, year, embark_date, disembark_date, countries, start_port, end_port, captain_name, yacht_id, hours_total, hours_sail, hours_engine, hours_over_6bf, miles, days, tidal_waters, cost_total, cost_per_person, image_logo_url, image_photo_url, image_route_url, description, created_at, updated_at, cruise_id FROM voyages WHERE owner_id = $1 AND org_id IS NULL ORDER BY year DESC, embark_date DESC
`

func (q *Queries) ListVoyages(ctx context.Context, ownerID int64) ([]Voyage, error) {
	rows, err := q.db.QueryContext(ctx, listVoyages, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Voyage
	for rows.Next() {
		var i Voyage
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.OrgID,
			&i.Name,
			&i.Year,
			&i.EmbarkDate,
			&i.DisembarkDate,
			&i.Countries,
			&i.StartPort,
			&i.EndPort,
			&i.CaptainName,
			&i.YachtID,
			&i.HoursTotal,
			&i.HoursSail,
			&i.HoursEngine,
			&i.HoursOver6bf,
			&i.Miles,
			&i.Days,
			&i.TidalWaters,
			&i.CostTotal,
			&i.CostPerPerson,
			&i.ImageLogoUrl,
			&i.ImagePhotoUrl,
			&i.ImageRouteUrl,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CruiseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrgVoyage = `-- name: UpdateOrgVoyage :exec
UPDATE voyages SET
    name = $1, year = $2, embark_date = $3, disembark_date = $4, countries = $5,
    start_port = $6, end_port = $7, captain_name = $8, yacht_id = $9,
    hours_total = $10, hours_sail = $11, hours_engine = $12, hours_over_6bf = $13,
    miles = $14, days = $15, tidal_waters = $16,
    cost_total = $17, cost_per_person = $18,
    image_logo_url = $19, image_photo_url = $20, image_route_url = $21, description = $22,
    cruise_id = $23,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $24 AND org_id = $25
`

type UpdateOrgVoyageParams struct {
	Name          string            `json:"name"`
	Year          types.NullInt64   `json:"year"`
	EmbarkDate    types.NullString  `json:"embark_date"`
	DisembarkDate types.NullString  `json:"disembark_date"`
	Countries     types.NullString  `json:"countries"`
	StartPort     types.NullString  `json:"start_port"`
	EndPort       types.NullString  `json:"end_port"`
	CaptainName   types.NullString  `json:"captain_name"`
	YachtID       types.NullInt64   `json:"yacht_id"`
	HoursTotal    float64           `json:"hours_total"`
	HoursSail     float64           `json:"hours_sail"`
	HoursEngine   float64           `json:"hours_engine"`
	HoursOver6bf  float64           `json:"hours_over_6bf"`
	Miles         float64           `json:"miles"`
	Days          int64             `json:"days"`
	TidalWaters   int64             `json:"tidal_waters"`
	CostTotal     types.NullFloat64 `json:"cost_total"`
	CostPerPerson types.NullFloat64 `json:"cost_per_person"`
	ImageLogoUrl  types.NullString  `json:"image_logo_url"`
	ImagePhotoUrl types.NullString  `json:"image_photo_url"`
	ImageRouteUrl types.NullString  `json:"image_route_url"`
	Description   types.NullString  `json:"description"`
	CruiseID      types.NullInt64   `json:"cruise_id"`
	ID            int64             `json:"id"`
	OrgID         types.NullInt64   `json:"org_id"`
}

func (q *Queries) UpdateOrgVoyage(ctx context.Context, arg UpdateOrgVoyageParams) error {
	_, err := q.db.ExecContext(ctx, updateOrgVoyage,
		arg.Name,
		arg.Year,
		arg.EmbarkDate,
		arg.DisembarkDate,
		arg.Countries,
		arg.StartPort,
		arg.EndPort,
		arg.CaptainName,
		arg.YachtID,
		arg.HoursTotal,
		arg.HoursSail,
		arg.HoursEngine,
		arg.HoursOver6bf,
		arg.Miles,
		arg.Days,
		arg.TidalWaters,
		arg.CostTotal,
		arg.CostPerPerson,
		arg.ImageLogoUrl,
		arg.ImagePhotoUrl,
		arg.ImageRouteUrl,
		arg.Description,
		arg.CruiseID,
		arg.ID,
		arg.OrgID,
	)
	return err
}

const updateVoyage = `-- name: UpdateVoyage :exec
UPDATE voyages SET
    name = $1, year = $2, embark_date = $3, disembark_date = $4, countries = $5,
    start_port = $6, end_port = $7, captain_name = $8, yacht_id = $9,
    hours_total = $10, hours_sail = $11, hours_engine = $12, hours_over_6bf = $13,
    miles = $14, days = $15, tidal_waters = $16,
    cost_total = $17, cost_per_person = $18,
    image_logo_url = $19, image_photo_url = $20, image_route_url = $21, description = $22,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $23 AND owner_id = $24 AND org_id IS NULL
`

type UpdateVoyageParams struct {
	Name          string            `json:"name"`
	Year          types.NullInt64   `json:"year"`
	EmbarkDate    types.NullString  `json:"embark_date"`
	DisembarkDate types.NullString  `json:"disembark_date"`
	Countries     types.NullString  `json:"countries"`
	StartPort     types.NullString  `json:"start_port"`
	EndPort       types.NullString  `json:"end_port"`
	CaptainName   types.NullString  `json:"captain_name"`
	YachtID       types.NullInt64   `json:"yacht_id"`
	HoursTotal    float64           `json:"hours_total"`
	HoursSail     float64           `json:"hours_sail"`
	HoursEngine   float64           `json:"hours_engine"`
	HoursOver6bf  float64           `json:"hours_over_6bf"`
	Miles         float64           `json:"miles"`
	Days          int64             `json:"days"`
	TidalWaters   int64             `json:"tidal_waters"`
	CostTotal     types.NullFloat64 `json:"cost_total"`
	CostPerPerson types.NullFloat64 `json:"cost_per_person"`
	ImageLogoUrl  types.NullString  `json:"image_logo_url"`
	ImagePhotoUrl types.NullString  `json:"image_photo_url"`
	ImageRouteUrl types.NullString  `json:"image_route_url"`
	Description   types.NullString  `json:"description"`
	ID            int64             `json:"id"`
	OwnerID       int64             `json:"owner_id"`
}

func (q *Queries) UpdateVoyage(ctx context.Context, arg UpdateVoyageParams) error {
	_, err := q.db.ExecContext(ctx, updateVoyage,
		arg.Name,
		arg.Year,
		arg.EmbarkDate,
		arg.DisembarkDate,
		arg.Countries,
		arg.StartPort,
		arg.EndPort,
		arg.CaptainName,
		arg.YachtID,
		arg.HoursTotal,
		arg.HoursSail,
		arg.HoursEngine,
		arg.HoursOver6bf,
		arg.Miles,
		arg.Days,
		arg.TidalWaters,
		arg.CostTotal,
		arg.CostPerPerson,
		arg.ImageLogoUrl,
		arg.ImagePhotoUrl,
		arg.ImageRouteUrl,
		arg.Description,
		arg.ID,
		arg.OwnerID,
	)
	return err
}
