// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voyage_opinions.sql

package sqlcdb

import (
	"context"

	types "github.com/marcinskalski/sailor-buddy/backend/internal/types"
)

const createVoyageOpinion = `-- name: CreateVoyageOpinion :one
INSERT INTO voyage_opinions (voyage_id, crew_member_id, file_path, file_format) VALUES ($1, $2, $3, $4) RETURNING id, voyage_id, crew_member_id, file_path, file_format, created_at
`

type CreateVoyageOpinionParams struct {
	VoyageID     int64  `json:"voyage_id"`
	CrewMemberID int64  `json:"crew_member_id"`
	FilePath     string `json:"file_path"`
	FileFormat   string `json:"file_format"`
}

// CreateVoyageOpinion
//
//	INSERT INTO voyage_opinions (voyage_id, crew_member_id, file_path, file_format) VALUES ($1, $2, $3, $4) RETURNING id, voyage_id, crew_member_id, file_path, file_format, created_at
func (q *Queries) CreateVoyageOpinion(ctx context.Context, arg CreateVoyageOpinionParams) (VoyageOpinion, error) {
	row := q.db.QueryRowContext(ctx, createVoyageOpinion,
		arg.VoyageID,
		arg.CrewMemberID,
		arg.FilePath,
		arg.FileFormat,
	)
	var i VoyageOpinion
	err := row.Scan(
		&i.ID,
		&i.VoyageID,
		&i.CrewMemberID,
		&i.FilePath,
		&i.FileFormat,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVoyageOpinion = `-- name: DeleteVoyageOpinion :exec
DELETE FROM voyage_opinions WHERE id = $1
`

// DeleteVoyageOpinion
//
//	DELETE FROM voyage_opinions WHERE id = $1
func (q *Queries) DeleteVoyageOpinion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteVoyageOpinion, id)
	return err
}

const getVoyageOpinion = `-- name: GetVoyageOpinion :one
SELECT id, voyage_id, crew_member_id, file_path, file_format, created_at FROM voyage_opinions WHERE id = $1
`

// GetVoyageOpinion
//
//	SELECT id, voyage_id, crew_member_id, file_path, file_format, created_at FROM voyage_opinions WHERE id = $1
func (q *Queries) GetVoyageOpinion(ctx context.Context, id int64) (VoyageOpinion, error) {
	row := q.db.QueryRowContext(ctx, getVoyageOpinion, id)
	var i VoyageOpinion
	err := row.Scan(
		&i.ID,
		&i.VoyageID,
		&i.CrewMemberID,
		&i.FilePath,
		&i.FileFormat,
		&i.CreatedAt,
	)
	return i, err
}

const listVoyageVoyageOpinions = `-- name: ListVoyageVoyageOpinions :many
SELECT vo.id, vo.voyage_id, vo.crew_member_id, vo.file_path, vo.file_format, vo.created_at, cm.full_name
FROM voyage_opinions vo
JOIN crew_members cm ON cm.id = vo.crew_member_id
WHERE vo.voyage_id = $1
ORDER BY cm.full_name
`

type ListVoyageVoyageOpinionsRow struct {
	ID           int64          `json:"id"`
	VoyageID     int64          `json:"voyage_id"`
	CrewMemberID int64          `json:"crew_member_id"`
	FilePath     string         `json:"file_path"`
	FileFormat   string         `json:"file_format"`
	CreatedAt    types.NullTime `json:"created_at"`
	FullName     string         `json:"full_name"`
}

// ListVoyageVoyageOpinions
//
//	SELECT vo.id, vo.voyage_id, vo.crew_member_id, vo.file_path, vo.file_format, vo.created_at, cm.full_name
//	FROM voyage_opinions vo
//	JOIN crew_members cm ON cm.id = vo.crew_member_id
//	WHERE vo.voyage_id = $1
//	ORDER BY cm.full_name
func (q *Queries) ListVoyageVoyageOpinions(ctx context.Context, voyageID int64) ([]ListVoyageVoyageOpinionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVoyageVoyageOpinions, voyageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVoyageVoyageOpinionsRow
	for rows.Next() {
		var i ListVoyageVoyageOpinionsRow
		if err := rows.Scan(
			&i.ID,
			&i.VoyageID,
			&i.CrewMemberID,
			&i.FilePath,
			&i.FileFormat,
			&i.CreatedAt,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVoyageOpinion = `-- name: UpsertVoyageOpinion :one
INSERT INTO voyage_opinions (voyage_id, crew_member_id, file_path, file_format)
VALUES ($1, $2, $3, $4)
ON CONFLICT (voyage_id, crew_member_id) DO UPDATE
SET file_path = EXCLUDED.file_path, file_format = EXCLUDED.file_format, created_at = CURRENT_TIMESTAMP
RETURNING id, voyage_id, crew_member_id, file_path, file_format, created_at
`

type UpsertVoyageOpinionParams struct {
	VoyageID     int64  `json:"voyage_id"`
	CrewMemberID int64  `json:"crew_member_id"`
	FilePath     string `json:"file_path"`
	FileFormat   string `json:"file_format"`
}

// UpsertVoyageOpinion
//
//	INSERT INTO voyage_opinions (voyage_id, crew_member_id, file_path, file_format)
//	VALUES ($1, $2, $3, $4)
//	ON CONFLICT (voyage_id, crew_member_id) DO UPDATE
//	SET file_path = EXCLUDED.file_path, file_format = EXCLUDED.file_format, created_at = CURRENT_TIMESTAMP
//	RETURNING id, voyage_id, crew_member_id, file_path, file_format, created_at
func (q *Queries) UpsertVoyageOpinion(ctx context.Context, arg UpsertVoyageOpinionParams) (VoyageOpinion, error) {
	row := q.db.QueryRowContext(ctx, upsertVoyageOpinion,
		arg.VoyageID,
		arg.CrewMemberID,
		arg.FilePath,
		arg.FileFormat,
	)
	var i VoyageOpinion
	err := row.Scan(
		&i.ID,
		&i.VoyageID,
		&i.CrewMemberID,
		&i.FilePath,
		&i.FileFormat,
		&i.CreatedAt,
	)
	return i, err
}
