// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: yachts.sql

package sqlcdb

import (
	"context"

	types "github.com/marcinskalski/sailor-buddy/backend/internal/types"
)

const countYachts = `-- name: CountYachts :one
SELECT COUNT(*)::BIGINT FROM yachts
`

// CountYachts
//
//	SELECT COUNT(*)::BIGINT FROM yachts
func (q *Queries) CountYachts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countYachts)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createYacht = `-- name: CreateYacht :one
INSERT INTO yachts (created_by, name, registration_no, yacht_type)
VALUES ($1, $2, $3, $4) RETURNING id, created_by, name, registration_no, yacht_type, created_at, updated_at
`

type CreateYachtParams struct {
	CreatedBy      types.NullInt64  `json:"created_by"`
	Name           string           `json:"name"`
	RegistrationNo types.NullString `json:"registration_no"`
	YachtType      types.NullString `json:"yacht_type"`
}

// CreateYacht
//
//	INSERT INTO yachts (created_by, name, registration_no, yacht_type)
//	VALUES ($1, $2, $3, $4) RETURNING id, created_by, name, registration_no, yacht_type, created_at, updated_at
func (q *Queries) CreateYacht(ctx context.Context, arg CreateYachtParams) (Yacht, error) {
	row := q.db.QueryRowContext(ctx, createYacht,
		arg.CreatedBy,
		arg.Name,
		arg.RegistrationNo,
		arg.YachtType,
	)
	var i Yacht
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Name,
		&i.RegistrationNo,
		&i.YachtType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteYacht = `-- name: DeleteYacht :exec
DELETE FROM yachts WHERE id = $1
`

// DeleteYacht
//
//	DELETE FROM yachts WHERE id = $1
func (q *Queries) DeleteYacht(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteYacht, id)
	return err
}

const getYacht = `-- name: GetYacht :one
SELECT id, created_by, name, registration_no, yacht_type, created_at, updated_at FROM yachts WHERE id = $1
`

// GetYacht
//
//	SELECT id, created_by, name, registration_no, yacht_type, created_at, updated_at FROM yachts WHERE id = $1
func (q *Queries) GetYacht(ctx context.Context, id int64) (Yacht, error) {
	row := q.db.QueryRowContext(ctx, getYacht, id)
	var i Yacht
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Name,
		&i.RegistrationNo,
		&i.YachtType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getYachtByName = `-- name: GetYachtByName :one
SELECT id, created_by, name, registration_no, yacht_type, created_at, updated_at FROM yachts WHERE name = $1
`

// GetYachtByName
//
//	SELECT id, created_by, name, registration_no, yacht_type, created_at, updated_at FROM yachts WHERE name = $1
func (q *Queries) GetYachtByName(ctx context.Context, name string) (Yacht, error) {
	row := q.db.QueryRowContext(ctx, getYachtByName, name)
	var i Yacht
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Name,
		&i.RegistrationNo,
		&i.YachtType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listYachts = `-- name: ListYachts :many
SELECT id, created_by, name, registration_no, yacht_type, created_at, updated_at FROM yachts ORDER BY name, id LIMIT $1 OFFSET $2
`

type ListYachtsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// ListYachts
//
//	SELECT id, created_by, name, registration_no, yacht_type, created_at, updated_at FROM yachts ORDER BY name, id LIMIT $1 OFFSET $2
func (q *Queries) ListYachts(ctx context.Context, arg ListYachtsParams) ([]Yacht, error) {
	rows, err := q.db.QueryContext(ctx, listYachts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Yacht
	for rows.Next() {
		var i Yacht
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.Name,
			&i.RegistrationNo,
			&i.YachtType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateYacht = `-- name: UpdateYacht :exec
UPDATE yachts SET name = $1, registration_no = $2, yacht_type = $3, updated_at = CURRENT_TIMESTAMP
WHERE id = $4
`

type UpdateYachtParams struct {
	Name           string           `json:"name"`
	RegistrationNo types.NullString `json:"registration_no"`
	YachtType      types.NullString `json:"yacht_type"`
	ID             int64            `json:"id"`
}

// UpdateYacht
//
//	UPDATE yachts SET name = $1, registration_no = $2, yacht_type = $3, updated_at = CURRENT_TIMESTAMP
//	WHERE id = $4
func (q *Queries) UpdateYacht(ctx context.Context, arg UpdateYachtParams) error {
	_, err := q.db.ExecContext(ctx, updateYacht,
		arg.Name,
		arg.RegistrationNo,
		arg.YachtType,
		arg.ID,
	)
	return err
}
