// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: yachts.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const createYacht = `-- name: CreateYacht :one
INSERT INTO yachts (owner_id, name, registration_no, yacht_type) VALUES ($1, $2, $3, $4) RETURNING id, owner_id, name, registration_no, yacht_type, created_at, updated_at
`

type CreateYachtParams struct {
	OwnerID        int64
	Name           string
	RegistrationNo sql.NullString
	YachtType      sql.NullString
}

func (q *Queries) CreateYacht(ctx context.Context, arg CreateYachtParams) (Yacht, error) {
	row := q.db.QueryRowContext(ctx, createYacht,
		arg.OwnerID,
		arg.Name,
		arg.RegistrationNo,
		arg.YachtType,
	)
	var i Yacht
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.RegistrationNo,
		&i.YachtType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteYacht = `-- name: DeleteYacht :exec
DELETE FROM yachts WHERE id = $1 AND owner_id = $2
`

type DeleteYachtParams struct {
	ID      int64
	OwnerID int64
}

func (q *Queries) DeleteYacht(ctx context.Context, arg DeleteYachtParams) error {
	_, err := q.db.ExecContext(ctx, deleteYacht, arg.ID, arg.OwnerID)
	return err
}

const getYacht = `-- name: GetYacht :one
SELECT id, owner_id, name, registration_no, yacht_type, created_at, updated_at FROM yachts WHERE id = $1 AND owner_id = $2
`

type GetYachtParams struct {
	ID      int64
	OwnerID int64
}

func (q *Queries) GetYacht(ctx context.Context, arg GetYachtParams) (Yacht, error) {
	row := q.db.QueryRowContext(ctx, getYacht, arg.ID, arg.OwnerID)
	var i Yacht
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.RegistrationNo,
		&i.YachtType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getYachtByName = `-- name: GetYachtByName :one
SELECT id, owner_id, name, registration_no, yacht_type, created_at, updated_at FROM yachts WHERE owner_id = $1 AND name = $2
`

type GetYachtByNameParams struct {
	OwnerID int64
	Name    string
}

func (q *Queries) GetYachtByName(ctx context.Context, arg GetYachtByNameParams) (Yacht, error) {
	row := q.db.QueryRowContext(ctx, getYachtByName, arg.OwnerID, arg.Name)
	var i Yacht
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.RegistrationNo,
		&i.YachtType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listYachts = `-- name: ListYachts :many
SELECT id, owner_id, name, registration_no, yacht_type, created_at, updated_at FROM yachts WHERE owner_id = $1 ORDER BY name
`

func (q *Queries) ListYachts(ctx context.Context, ownerID int64) ([]Yacht, error) {
	rows, err := q.db.QueryContext(ctx, listYachts, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Yacht
	for rows.Next() {
		var i Yacht
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.RegistrationNo,
			&i.YachtType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateYacht = `-- name: UpdateYacht :exec
UPDATE yachts SET name = $1, registration_no = $2, yacht_type = $3, updated_at = CURRENT_TIMESTAMP WHERE id = $4 AND owner_id = $5
`

type UpdateYachtParams struct {
	Name           string
	RegistrationNo sql.NullString
	YachtType      sql.NullString
	ID             int64
	OwnerID        int64
}

func (q *Queries) UpdateYacht(ctx context.Context, arg UpdateYachtParams) error {
	_, err := q.db.ExecContext(ctx, updateYacht,
		arg.Name,
		arg.RegistrationNo,
		arg.YachtType,
		arg.ID,
		arg.OwnerID,
	)
	return err
}
